ladderproblems = [
    {serial_no : 1, problem_name : 'Flowers',contest_id : '474', problem_level :  'D'} ,
    {serial_no : 2, problem_name : 'Prizes, Prizes, more Prizes',contest_id : '208', problem_level :  'D'} ,
    {serial_no : 3, problem_name : 'Xenia and Bit Operations',contest_id : '339', problem_level :  'D'} ,
    {serial_no : 4, problem_name : 'Vasya and Chess',contest_id : '493', problem_level :  'D'} ,
    {serial_no : 5, problem_name : 'Mashmokh and ACM',contest_id : '414', problem_level :  'D'} ,
    {serial_no : 6, problem_name : 'Multiplication Table',contest_id : '448', problem_level :  'D'} ,
    {serial_no : 7, problem_name : 'Unbearable Controversy of Being', contest_id :'489', problem_level :  'D'} ,
    {serial_no : 8, problem_name : "Caesar's Legions",contest_id : '118', problem_level :  'D'} ,
    {serial_no : 9, problem_name : 'Colorful Graph', contest_id :'246', problem_level :  'D'} ,
    {serial_no : 10, problem_name :  'Little Girl and Maximum XOR',contest_id : '276', problem_level :  'D'} ,
    {serial_no : 11, problem_name :  'Common Divisors', contest_id :'182', problem_level :  'D'} ,
    {serial_no : 12, problem_name :  'Magic Box', contest_id :'231', problem_level :  'D'} ,
    {serial_no : 13, problem_name :  'Good Sequences', contest_id :'264', problem_level :  'D'} ,
    {serial_no : 14, problem_name :  'Password', contest_id :'126', problem_level :  'D'} ,
    {serial_no : 15, problem_name :  'Greg and Graph',contest_id : '295', problem_level :  'D'} ,
    {serial_no : 16, problem_name :  'Working out', contest_id :'429', problem_level :  'D'} ,
    {serial_no : 17, problem_name :  'Count Good Substrings',contest_id : '451', problem_level :  'D'} ,
    {serial_no : 18, problem_name :  'Good Substrings', contest_id :'271', problem_level :  'D'} ,
    {serial_no : 19, problem_name :  'Long Path', contest_id :'407', problem_level :  'D'} ,
    {serial_no : 20, problem_name :  'Maximum Value', contest_id :'484', problem_level :  'D'} ,
    {serial_no : 21, problem_name :  'Greenhouse Effect', contest_id :'269', problem_level :  'D'} ,
    {serial_no : 22, problem_name :  'Red-Green Towers', contest_id :'478', problem_level :  'D'} ,
    {serial_no : 23, problem_name :  'Maximum Submatrix 2', contest_id :'375', problem_level :  'D'} ,
    {serial_no : 24, problem_name :  'Cow Program', contest_id :'283', problem_level :  'D'} ,
    {serial_no : 25, problem_name :  'Biridian Forest', contest_id :'329', problem_level :  'D'} ,
    {serial_no : 26, problem_name :  'Andrey and Problem', contest_id :'442', problem_level :  'D'} ,
    {serial_no : 27, problem_name :  'DZY Loves Modification', contest_id :'446', problem_level :  'D'} ,
    {serial_no : 28, problem_name :  'Zero Tree', contest_id :'274', problem_level :  'D'} ,
    {serial_no : 29, problem_name :  'Prefixes and Suffixes', contest_id :'432', problem_level :  'D'} ,
    {serial_no : 30, problem_name :  'Queue',contest_id : '91', problem_level :  'D'} ,
    {serial_no : 31, problem_name :  'Chips', contest_id :'333', problem_level :  'D'} ,
    {serial_no : 32, problem_name :  'Valid Sets',contest_id : '486', problem_level :  'D'} ,
    {serial_no : 33, problem_name :  'Pair of Numbers',contest_id : '359', problem_level :  'D'} ,
    {serial_no : 34, problem_name :  'Planets',contest_id : '229', problem_level :  'D'} ,
    {serial_no : 35, problem_name :  'Queue',contest_id : '353', problem_level :  'D'} ,
    {serial_no : 36, problem_name :  'Petya and Divisors',contest_id : '111', problem_level :  'D'} ,
    {serial_no : 37, problem_name :  'Obsessive String', contest_id :'494', problem_level :  'D'} ,
    {serial_no : 38, problem_name :  'Dima and Bacteria', contest_id :'400', problem_level :  'D'} ,
    {serial_no : 39, problem_name :  'Psychos in a Line', contest_id :'319', problem_level :  'D'} ,
    {serial_no : 40, problem_name :  'Ciel and Duel', contest_id :'321', problem_level :  'D'} ,
    {serial_no : 41, problem_name :  'Falling Anvils',contest_id : '77', problem_level :  'D'} ,
    {serial_no : 42, problem_name :  'Hit Ball',contest_id : '203', problem_level :  'D'} ,
    {serial_no : 43, problem_name :  'Toy Sum',contest_id : '405', problem_level :  'D'} ,
    {serial_no : 44, problem_name :  'Lucky Common Subsequence',contest_id : '346', problem_level :  'D'} ,
    {serial_no : 45, problem_name :  'Two Paths',contest_id : '14', problem_level :  'D'} ,
    {serial_no : 46, problem_name :  'Help General', contest_id :'142', problem_level :  'D'} ,
    {serial_no : 47, problem_name :  'Dima and Two Sequences', contest_id :'272', problem_level :  'D'} ,
    {serial_no : 48, problem_name :  'How many trees?',contest_id : '9', problem_level :  'D'} ,
    {serial_no : 49, problem_name :  'Lucky Number 2', contest_id :'145', problem_level :  'D'} ,
    {serial_no : 50, problem_name :  'Cinema',contest_id : '234', problem_level :  'D'} ,
    {serial_no : 51, problem_name :  'Wizards and Huge Prize',contest_id : '167', problem_level :  'D'} ,
    {serial_no : 52, problem_name :  'Apple Tree',contest_id : '348', problem_level :  'D'} ,
    {serial_no : 53, problem_name :  'Yaroslav and Time', contest_id :'301', problem_level :  'D'} ,
    {serial_no : 54, problem_name :  'Numbers',contest_id : '213', problem_level :  'D'} ,
    {serial_no : 55, problem_name :  'Treasure Island', contest_id :'106', problem_level :  'D'} ,
    {serial_no : 56, problem_name :  'Book of Evil', contest_id :'337', problem_level :  'D'} ,
    {serial_no : 57, problem_name :  'Sereja and Periods',contest_id : '314', problem_level :  'D'} ,
    {serial_no : 58, problem_name :  'Infinite Maze', contest_id :'196', problem_level :  'D'} ,
    {serial_no : 59, problem_name :  'Playing with Permutations',contest_id : '251', problem_level :  'D'} ,
    {serial_no : 60, problem_name :  'Doctor',contest_id : '83', problem_level :  'D'} ,
    {serial_no : 61, problem_name :  'Animals',contest_id : '35', problem_level :  'D'} ,
    {serial_no : 62, problem_name :  'Mushroom Scientists', contest_id :'185', problem_level :  'D'} ,
    {serial_no : 63, problem_name :  'Tennis Game',contest_id : '496', problem_level :  'D'} ,
    {serial_no : 64, problem_name :  'Buses', contest_id :'101', problem_level :  'D'} ,
    {serial_no : 65, problem_name :  'String',contest_id : '128', problem_level :  'D'} ,
    {serial_no : 66, problem_name :  'Shifting', contest_id :'286', problem_level :  'D'} ,
    {serial_no : 67, problem_name :  'Boring Partition',contest_id : '238', problem_level :  'D'} ,
    {serial_no : 68, problem_name :  'Analyzing Polyline', contest_id :'195', problem_level :  'D'} ,
    {serial_no : 69, problem_name :  'Vasya and Types',contest_id : '87', problem_level :  'D'} ,
    {serial_no : 70, problem_name :  'Lizards and Basements 2', contest_id :'6', problem_level :  'D'} ,
    {serial_no : 71, problem_name :  'Constellation',contest_id : '32', problem_level :  'D'} ,
    {serial_no : 72, problem_name :  'Pawn', contest_id :'41', problem_level :  'D'} ,
    {serial_no : 73, problem_name :  'Journey', contest_id :'43', problem_level :  'D'} ,
    {serial_no : 74, problem_name :  'Tanya and Password', contest_id :'508', problem_level :  'D'} ,
    {serial_no : 75, problem_name :  'Demonstration', contest_id :'191', problem_level :  'D'} ,
    {serial_no : 76, problem_name :  'Big Maximum Sum', contest_id :'75', problem_level :  'D'} ,
    {serial_no : 77, problem_name :  'The Child and Zoo',contest_id : '437', problem_level :  'D'} ,
    {serial_no : 78, problem_name :  'Mr. Bender and Square',contest_id : '255', problem_level :  'D'} ,
    {serial_no : 79, problem_name :  'Special Grid', contest_id :'435', problem_level :  'D'} ,
    {serial_no : 80, problem_name :  'Name That Tune', contest_id :'498', problem_level :  'D'} ,
    {serial_no : 81, problem_name :  'Ring Road 2',contest_id : '27', problem_level :  'D'} ,
    {serial_no : 82, problem_name :  'Russian Roulette',contest_id : '103', problem_level: 'C'} ,
    {serial_no : 83, problem_name :  'Snake',contest_id : '225', problem_level :  'D'} ,
    {serial_no : 84, problem_name :  'Upgrading Array',contest_id : '402', problem_level :  'D'} ,
    {serial_no : 85, problem_name :  'Edges in MST', contest_id :'160', problem_level :  'D'} ,
    {serial_no : 86, problem_name :  'Fools and Foolproof Roads', contest_id :'362', problem_level :  'D'} ,
    {serial_no : 87, problem_name :  'End of Exams', contest_id :'93', problem_level :  'D'} ,
    {serial_no : 88, problem_name :  'Restoring Numbers', contest_id :'509', problem_level :  'D'} ,
    {serial_no : 89, problem_name :  'Cats Transport', contest_id :'311', problem_level :  'D'} ,
    {serial_no : 90, problem_name :  'Broken Monitor', contest_id :'370', problem_level :  'D'} ,
    {serial_no : 91, problem_name :  'The Minimum Number of Variables', contest_id :'279', problem_level :  'D'} ,
    {serial_no : 92, problem_name :  'Volcanoes', contest_id :'383', problem_level :  'D'} ,
    {serial_no : 93, problem_name :  'Widget Library',contest_id : '89', problem_level :  'D'} ,
    {serial_no : 94, problem_name :  'Misha and Permutations Summation',contest_id : '501', problem_level :  'D'} ,
    {serial_no : 95, problem_name :  'BerDonalds', contest_id :'266', problem_level :  'D'} ,
    {serial_no : 96, problem_name :  'Tower of Hanoi',contest_id : '392', problem_level :  'D'} ,
    {serial_no : 97, problem_name :  "Mr. Kitayuta's Technology",contest_id : '505', problem_level :  'D'} ,
    {serial_no : 98, problem_name :  'Shoe Store', contest_id :'166', problem_level :  'D'} ,
    {serial_no : 99, problem_name :  'Inna and Sweet Matrix',contest_id : '390', problem_level :  'D'} ,
    {serial_no : 100, problem_name :  'Help King',contest_id : '98', problem_level :  'D'}
]

module.exports = {ladderproblems}
