ladderproblems = [
    {serial_no: 1, problem_name : 'Given Length and Sum of Digits...', contest_id : '489', problem_level :  'C'} ,
    {serial_no: 2, problem_name : 'Number of Ways',  contest_id :'466', problem_level :  'C'} ,
    {serial_no: 3, problem_name : 'Team',  contest_id :'401', problem_level :  'C'} ,
    {serial_no: 4, problem_name : 'Exams', contest_id : '479', problem_level :  'C'} ,
    {serial_no: 5, problem_name : 'Boredom', contest_id : '455', problem_level :  'C'} ,
    {serial_no: 6, problem_name : 'Table Decorations',  contest_id :'478', problem_level :  'C'} ,
    {serial_no: 7, problem_name : 'Beautiful Sets of Points', contest_id : '268', problem_level :  'C'} ,
    {serial_no: 8, problem_name : 'k-Tree',  contest_id :'431', problem_level :  'C'} ,
    {serial_no: 9, problem_name : 'Valera and Tubes ',  contest_id :'441', problem_level :  'C'} ,
    {serial_no: 10,problem_name :  'Palindrome Transformation', contest_id : '486', problem_level :  'C'} ,
    {serial_no: 11,problem_name :  'Fixing Typos',  contest_id :'363', problem_level :  'C'} ,
    {serial_no: 12,problem_name :  'Hacking Cypher', contest_id : '490', problem_level :  'C'} ,
    {serial_no: 13,problem_name :  'Gargari and Bishops',  contest_id :'463', problem_level :  'C'} ,
    {serial_no: 14,problem_name :  'Pocket Book',  contest_id :'152', problem_level :  'C'} ,
    {serial_no: 15,problem_name :  'Lucky Sum of Digits',  contest_id :'109', problem_level :  'C'} ,
    {serial_no: 16,problem_name :  'Arithmetic Progression',  contest_id :'382', problem_level :  'C'} ,
    {serial_no: 17,problem_name :  'Fox and Box Accumulation',  contest_id :'388', problem_level :  'C'} ,
    {serial_no: 18,problem_name :  "Hexadecimal's Numbers",  contest_id :'9', problem_level :  'C'} ,
    {serial_no: 19,problem_name :  'Xenia and Weights', contest_id : '339', problem_level :  'C'} ,
    {serial_no: 20,problem_name :  'Bombs',  contest_id :'350', problem_level :  'C'} ,
    {serial_no: 21,problem_name :  'Pashmak and Buses', contest_id : '459', problem_level :  'C'} ,
    {serial_no: 22,problem_name :  'Little Elephant and Problem',  contest_id :'220', problem_level :  'C'} ,
    {serial_no: 23,problem_name :  'Maze',  contest_id :'377', problem_level :  'C'} ,
    {serial_no: 24,problem_name :  'Ice Skating',  contest_id :'217', problem_level :  'C'} ,
    {serial_no: 25,problem_name :  'Hamburgers',  contest_id :'371', problem_level :  'C'} ,
    {serial_no: 26,problem_name :  'Bear and Prime Numbers',  contest_id :'385', problem_level :  'C'} ,
    {serial_no: 27,problem_name :  'History',  contest_id :'137', problem_level :  'C'} ,
    {serial_no: 28,problem_name :  'Checkposts',  contest_id :'427', problem_level :  'C'} ,
    {serial_no: 29,problem_name :  'Mashmokh and Numbers', contest_id : '414', problem_level :  'C'} ,
    {serial_no: 30,problem_name :  'Ladder',  contest_id :'279', problem_level :  'C'} ,
    {serial_no: 31,problem_name :  'Escape from Stones', contest_id : '264', problem_level :  'C'} ,
    {serial_no: 32,problem_name :  'Division into Teams',  contest_id :'149', problem_level :  'C'} ,
    {serial_no: 33,problem_name :  'Barcode',  contest_id :'225', problem_level :  'C'} ,
    {serial_no: 34,problem_name :  'Stripe',  contest_id :'18', problem_level :  'C'} ,
    {serial_no: 35,problem_name :  'Mafia',  contest_id :'348', problem_level :  'C'} ,
    {serial_no: 36,problem_name :  'Cows and Sequence',  contest_id :'283', problem_level :  'C'} ,
    {serial_no: 37,problem_name :  'To Add or Not to Add',  contest_id :'231', problem_level :  'C'} ,
    {serial_no: 38,problem_name :  'Xor-tree',  contest_id :'429', problem_level :  'C'} ,
    {serial_no: 39,problem_name :  'LCM Challenge',  contest_id :'235', problem_level :  'C'} ,
    {serial_no: 40,problem_name :  'Rational Resistance',  contest_id :'343', problem_level :  'C'} ,
    {serial_no: 41,problem_name :  'Points on Line',  contest_id :'251', problem_level :  'C'} ,
    {serial_no: 42,problem_name :  'No to Palindromes!',  contest_id :'464', problem_level :  'C'} ,
    {serial_no: 43,problem_name :  'Magic Formulas', contest_id : '424', problem_level :  'C'} ,
    {serial_no: 44,problem_name :  'Beautiful Numbers',  contest_id :'300', problem_level :  'C'} ,
    {serial_no: 45,problem_name :  'Quiz',  contest_id :'337', problem_level :  'C'} ,
    {serial_no: 46,problem_name :  'Replacement',  contest_id :'135', problem_level :  'C'} ,
    {serial_no: 47,problem_name :  'Vasya and Robot',  contest_id :'354', problem_level :  'C'} ,
    {serial_no: 48,problem_name :  'Captain Marmot',  contest_id :'474', problem_level :  'C'} ,
    {serial_no: 49,problem_name :  'Win or Freeze', contest_id :'150', problem_level :  'C'} ,
    {serial_no: 50,problem_name :  'Matrix',  contest_id :'364', problem_level :  'C'} ,
    {serial_no: 51,problem_name :  'Little Frog',  contest_id :'53', problem_level :  'C'} ,
    {serial_no: 52,problem_name :  'Lucky Sum', contest_id : '121', problem_level :  'C'} ,
    {serial_no: 53,problem_name :  'Fight the Monster',  contest_id :'487', problem_level :  'C'} ,
    {serial_no: 54,problem_name :  'Triangle',  contest_id :'407', problem_level :  'C'} ,
    {serial_no: 55,problem_name :  'View Angle',  contest_id :'257', problem_level :  'C'} ,
    {serial_no: 56,problem_name :  "King's Path",  contest_id :'242', problem_level :  'C'} ,
    {serial_no: 57,problem_name :  'Round Table Knights', contest_id : '71', problem_level :  'C'} ,
    {serial_no: 58,problem_name :  'Purification', contest_id : '329', problem_level :  'C'} ,
    {serial_no: 59,problem_name :  'Maxim and Discounts',  contest_id :'261', problem_level :  'C'} ,
    {serial_no: 60,problem_name :  'The Closest Pair', contest_id : '311', problem_level :  'C'} ,
    {serial_no: 61,problem_name :  'Divisible by Seven',  contest_id :'375', problem_level :  'C'} ,
    {serial_no: 62,problem_name :  'Hometask',  contest_id :'154', problem_level :  'C'} ,
    {serial_no: 63,problem_name :  'Little Elephant and Interval',  contest_id :'204', problem_level :  'C'} ,
    {serial_no: 64,problem_name :  'Dorm Water Supply',  contest_id :'107', problem_level :  'C'} ,
    {serial_no: 65,problem_name :  'Shaass and Lights',  contest_id :'294', problem_level :  'C'} ,
    {serial_no: 66,problem_name :  'Prime Number', contest_id : '359', problem_level :  'C'} ,
    {serial_no: 67,problem_name :  'The Brand New Function', contest_id : '243', problem_level :  'C'} ,
    {serial_no: 68,problem_name :  'About Bacteria', contest_id : '198', problem_level :  'C'} ,
    {serial_no: 69,problem_name :  'Malek Dance Club', contest_id : '319', problem_level :  'C'} ,
    {serial_no: 70,problem_name :  'Dima and Containers',  contest_id :'358', problem_level :  'C'} ,
    {serial_no: 71,problem_name :  'Trains',  contest_id :'87', problem_level :  'C'} ,
    {serial_no: 72,problem_name :  'Almost Arithmetical Progression',  contest_id :'255', problem_level :  'C'} ,
    {serial_no: 73,problem_name :  'Newspaper Headline',  contest_id :'91', problem_level :  'C'} ,
    {serial_no: 74,problem_name :  'Inna and Dima',  contest_id :'374', problem_level :  'C'} ,
    {serial_no: 75,problem_name :  'Hiring Staff',  contest_id :'216', problem_level :  'C'} ,
    {serial_no: 76,problem_name :  'STL',  contest_id :'190', problem_level :  'C'} ,
    {serial_no: 77,problem_name :  'Prime Permutation',  contest_id :'123', problem_level :  'C'} ,
    {serial_no: 78,problem_name :  'Four Segments',  contest_id :'14', problem_level :  'C'} ,
    {serial_no: 79,problem_name :  'Fire Again',  contest_id :'35', problem_level :  'C'} ,
    {serial_no: 80,problem_name :  'Below the Diagonal',  contest_id :'266', problem_level :  'C'} ,
    {serial_no: 81,problem_name :  'Mail Stamps',  contest_id :'29', problem_level :  'C'} ,
    {serial_no: 82,problem_name :  'Grammar Lessons', contest_id : '113', problem_level :  'C'} ,
    {serial_no: 83,problem_name :  'Bracket Sequence', contest_id : '223', problem_level :  'C'} ,
    {serial_no: 84,problem_name :  'Heroes', contest_id : '77', problem_level :  'C'} ,
    {serial_no: 85,problem_name :  'Literature Lesson',  contest_id :'138', problem_level :  'C'} ,
    {serial_no: 86,problem_name :  'Reducing Fractions',  contest_id :'222', problem_level :  'C'} ,
    {serial_no: 87,problem_name :  'Game',  contest_id :'213', problem_level :  'C'} ,
    {serial_no: 88,problem_name :  'Cutting Figure',  contest_id :'193', problem_level :  'C'} ,
    {serial_no: 89,problem_name :  'Trees',  contest_id :'58', problem_level :  'C'} ,
    {serial_no: 90,problem_name :  'Hockey',  contest_id :'95', problem_level :  'C'} ,
    {serial_no: 91,problem_name :  'Schedule',  contest_id :'31', problem_level :  'C'} ,
    {serial_no: 92,problem_name :  'Rectangle Puzzle',  contest_id :'280', problem_level :  'C'} ,
    {serial_no: 93,problem_name :  'Disposition',  contest_id :'49', problem_level :  'C'} ,
    {serial_no: 94,problem_name :  'Flea',  contest_id :'32', problem_level :  'C'} ,
    {serial_no: 95,problem_name :  'Help Victoria the Wise',  contest_id :'98', problem_level :  'C'} ,
    {serial_no: 96,problem_name :  'Corporation Mail',  contest_id :'56', problem_level :  'C'} ,
    {serial_no: 97,problem_name : 'Optimal Sum',  contest_id :'182', problem_level :  'C'} ,
    {serial_no: 98,problem_name : 'On Number of Decompositions into Multipliers',  contest_id :'396', problem_level :  'C'} ,
    {serial_no: 99,problem_name : 'Blocked Points',  contest_id :'392', problem_level :  'C'} ,
    {serial_no: 100, problem_name : 'Crossword',  contest_id :'47', problem_level :  'C'}
]
module.exports = {ladderproblems}


