ladderproblems = [
    {serial_no: 1, problem_name : 'Watermelon', contest_id : '4', problem_level: 'A'} ,
    {serial_no: 2, problem_name : 'Way Too Long Words', contest_id : '71', problem_level: 'A'} ,
    {serial_no: 3, problem_name : 'String Task', contest_id : '118', problem_level: 'A'} ,
    {serial_no: 4, problem_name : 'Petya and Strings', contest_id : '112', problem_level:'A'} ,
    {serial_no: 5, problem_name : 'Helpful Maths', contest_id : '339', problem_level: 'A'} ,
    {serial_no: 6, problem_name : 'Twins', contest_id : '160', problem_level: 'A'} ,
    {serial_no: 7, problem_name : 'Chat room', contest_id : '58', problem_level: 'A'} ,
    {serial_no: 8, problem_name : 'Lucky Division', contest_id : '122', problem_level: 'A'} ,
    {serial_no: 9, problem_name : 'Presents', contest_id : '136',  problem_level:  'A'} ,
    {serial_no: 10,problem_name : 'Beautiful Matrix', contest_id :'263',  problem_level:  'A'} ,
    {serial_no: 11,problem_name : 'Arrival of the General', contest_id :'144',  problem_level:  'A'} ,
    {serial_no: 12,problem_name : 'Game With Sticks', contest_id :'451',  problem_level:  'A'} ,
    {serial_no: 13,problem_name : 'Games', contest_id :'268',  problem_level:  'A'} ,
    {serial_no: 14,problem_name : 'Dubstep', contest_id :'208',  problem_level:  'A'} ,
    {serial_no: 15,problem_name : 'Young Physicist', contest_id :'69',  problem_level:  'A'} ,
    {serial_no: 16,problem_name : 'Puzzles', contest_id :'337',  problem_level:  'A'} ,
    {serial_no: 17,problem_name : 'Expression', contest_id :'479',  problem_level:  'A'} ,
    {serial_no: 18,problem_name : 'Anton and Letters', contest_id :'443',  problem_level:  'A'} ,
    {serial_no: 19,problem_name : 'I Wanna Be the Guy', contest_id :'469',  problem_level:  'A'} ,
    {serial_no: 20,problem_name : 'Even Odds', contest_id :'318',  problem_level:  'A'} ,
    {serial_no: 21,problem_name : 'Cheap Travel', contest_id :'466',  problem_level:  'A'} ,
    {serial_no: 22,problem_name : 'Ilya and Bank Account', contest_id :'313',  problem_level:  'A'} ,
    {serial_no: 23,problem_name : 'Pashmak and Garden', contest_id :'459',  problem_level:  'A'} ,
    {serial_no: 24,problem_name : 'Dragons', contest_id :'230',  problem_level:  'A'} ,
    {serial_no: 25,problem_name : 'Dreamoon and Stairs', contest_id :'476',  problem_level:  'A'} ,
    {serial_no: 26,problem_name : 'Team Olympiad', contest_id :'490',  problem_level:  'A'} ,
    {serial_no: 27,problem_name : 'Devu, the Singer and Churu, the Joker',contest_id : '439',  problem_level:  'A'} ,
    {serial_no: 28,problem_name : 'Fox And Snake',contest_id : '510',  problem_level:  'A'} ,
    {serial_no: 29,problem_name : 'IQ test', contest_id :'25',  problem_level:  'A'} ,
    {serial_no: 30,problem_name : 'Choosing Teams', contest_id :'432',  problem_level:  'A'} ,
    {serial_no: 31,problem_name : 'Cakeminator', contest_id :'330',  problem_level:  'A'} ,
    {serial_no: 32,problem_name : 'Valera and Antique Items', contest_id :'441',  problem_level:  'A'} ,
    {serial_no: 33,problem_name : 'Appleman and Easy Task',contest_id : '462',  problem_level:  'A'} ,
    {serial_no: 34,problem_name : 'Bear and Raspberry', contest_id :'385',  problem_level:  'A'} ,
    {serial_no: 35,problem_name : 'Lunch Rush', contest_id :'276',  problem_level:  'A'} ,
    {serial_no: 36,problem_name : 'Laptops', contest_id :'456',  problem_level:  'A'} ,
    {serial_no: 37,problem_name : 'Soft Drinking', contest_id :'151',  problem_level:  'A'} ,
    {serial_no: 38,problem_name : 'Playing with Dice', contest_id :'378',  problem_level:  'A'} ,
    {serial_no: 39,problem_name : 'Minimum Difficulty', contest_id :'496',  problem_level:  'A'} ,
    {serial_no: 40,problem_name : "Greg's Workout", contest_id :'255',  problem_level:  'A'} ,
    {serial_no: 41,problem_name : 'Counterexample ', contest_id :'483',  problem_level:  'A'} ,
    {serial_no: 42,problem_name : 'Valera and X', contest_id :'404',  problem_level:  'A'} ,
    {serial_no: 43,problem_name : 'Perfect Permutation', contest_id :'233',  problem_level:  'A'} ,
    {serial_no: 44,problem_name : 'Watching a movie', contest_id :'499',  problem_level:  'A'} ,
    {serial_no: 45,problem_name : 'Supercentral Point', contest_id :'165',  problem_level:  'A'} ,
    {serial_no: 46,problem_name : 'Roma and Lucky Numbers', contest_id :'262',  problem_level:  'A'} ,
    {serial_no: 47,problem_name : 'Contest', contest_id :'501',  problem_level:  'A'} ,
    {serial_no: 48,problem_name : 'Cut Ribbon', contest_id :'189',  problem_level:  'A'} ,
    {serial_no: 49,problem_name : 'TL', contest_id :'350',  problem_level:  'A'} ,
    {serial_no: 50,problem_name : 'Marks', contest_id :'152',  problem_level:  'A'} ,
    {serial_no: 51,problem_name : 'Colorful Stones (Simplified Edition)',contest_id : '265',  problem_level:  'A'} ,
    {serial_no: 52,problem_name : 'Domino', contest_id :'353',  problem_level:  'A'} ,
    {serial_no: 53,problem_name : 'Cifera', contest_id :'114',  problem_level:  'A'} ,
    {serial_no: 54,problem_name : 'Array', contest_id :'300',  problem_level:  'A'} ,
    {serial_no: 55,problem_name : 'Fox and Number Game', contest_id :'389',  problem_level:  'A'} ,
    {serial_no: 56,problem_name : 'Giga Tower', contest_id :'488',  problem_level:  'A'} ,
    {serial_no: 57,problem_name : 'Parallelepiped', contest_id :'224',  problem_level:  'A'} ,
    {serial_no: 58,problem_name : 'DZY Loves Chessboard', contest_id :'445',  problem_level:  'A'} ,
    {serial_no: 59,problem_name : 'Football', contest_id :'43',  problem_level:  'A'} ,
    {serial_no: 60,problem_name : 'Life Without Zeros', contest_id :'75',  problem_level:  'A'} ,
    {serial_no: 61,problem_name : 'Yaroslav and Permutations', contest_id :'296',  problem_level:  'A'} ,
    {serial_no: 62,problem_name : 'Collecting Beats is Fun', contest_id :'373',  problem_level:  'A'} ,
    {serial_no: 63,problem_name : 'Levko and Table', contest_id :'361',  problem_level:  'A'} ,
    {serial_no: 64,problem_name : 'Vasya and Digital Root', contest_id :'355',  problem_level:  'A'} ,
    {serial_no: 65,problem_name : 'Two Bags of Potatoes', contest_id :'239',  problem_level:  'A'} ,
    {serial_no: 66,problem_name : 'The Child and Homework', contest_id :'437',  problem_level:  'A'} ,
    {serial_no: 67,problem_name : 'Soroban', contest_id :'363',  problem_level:  'A'} ,
    {serial_no: 68,problem_name : 'Line to Cashier', contest_id :'408',  problem_level:  'A'} ,
    {serial_no: 69,problem_name : 'Lever', contest_id :'376',  problem_level:  'A'} ,
    {serial_no: 70,problem_name : 'Table', contest_id :'359',  problem_level:  'A'} ,
    {serial_no: 71,problem_name : 'Eugeny and Array', contest_id :'302',  problem_level:  'A'} ,
    {serial_no: 72,problem_name : 'Dima and Continuous Line', contest_id :'358',  problem_level:  'A'} ,
    {serial_no: 73,problem_name : 'Reconnaissance 2', contest_id :'34',  problem_level:  'A'} ,
    {serial_no: 74,problem_name : 'Help Vasilisa the Wise 2', contest_id :'143',  problem_level:  'A'} ,
    {serial_no: 75,problem_name : 'Comparing Strings', contest_id :'186',  problem_level:  'A'} ,
    {serial_no: 76,problem_name : 'Palindromic Times', contest_id :'108',  problem_level:  'A'} ,
    {serial_no: 77,problem_name : 'Guess a number!', contest_id :'416',  problem_level:  'A'} ,
    {serial_no: 78,problem_name : 'Exams', contest_id :'194',  problem_level:  'A'} ,
    {serial_no: 79,problem_name : 'Card Game', contest_id :'106',  problem_level:  'A'} ,
    {serial_no: 80,problem_name : 'Sockets', contest_id :'257',  problem_level:  'A'} ,
    {serial_no: 81,problem_name : 'Snow Footprints', contest_id :'298',  problem_level:  'A'} ,
    {serial_no: 82,problem_name : 'Point on Spiral', contest_id :'279',  problem_level:  'A'} ,
    {serial_no: 83,problem_name : 'Next Test', contest_id :'27',  problem_level:  'A'} ,
    {serial_no: 84,problem_name : 'Rook, Bishop and King',contest_id : '370',  problem_level:  'A'} ,
    {serial_no: 85,problem_name : 'Sleuth', contest_id :'49',  problem_level:  'A'} ,
    {serial_no: 86,problem_name : 'Cows and Primitive Roots', contest_id :'284',  problem_level:  'A'} ,
    {serial_no: 87,problem_name : 'Funky Numbers', contest_id :'192',  problem_level:  'A'} ,
    {serial_no: 88,problem_name : 'Bar', contest_id :'56',  problem_level:  'A'} ,
    {serial_no: 89,problem_name : 'Lefthanders and Righthanders ', contest_id :'234',  problem_level:  'A'} ,
    {serial_no: 90,problem_name : 'Worms Evolution', contest_id :'31',  problem_level:  'A'} ,
    {serial_no: 91,problem_name : 'Strange Addition',contest_id : '305',  problem_level:  'A'} ,
    {serial_no: 92,problem_name : 'Plate Game', contest_id :'197',  problem_level:  'A'} ,
    {serial_no: 93,problem_name : 'Shell Game', contest_id :'35',  problem_level:  'A'} ,
    {serial_no: 94,problem_name : 'Chord',contest_id : '88',  problem_level:  'A'} ,
    {serial_no: 95,problem_name : 'Triangle',contest_id : '18',  problem_level:  'A'} ,
    {serial_no: 96,problem_name : 'Inna and Pink Pony',contest_id : '374',  problem_level:  'A'} ,
    {serial_no: 97,problem_name : 'Nineteen',contest_id : '393',  problem_level:  'A'} ,
    {serial_no: 98,problem_name : 'Inna and Alarm Clock',contest_id : '390',  problem_level:  'A'} ,
    {serial_no: 99,problem_name : "On Segment's Own Points",contest_id : '397',  problem_level:  'A'} ,
    {serial_no: 100, problem_name:'Cinema', contest_id : '200',  problem_level:  'A'}
]
 

module.exports = {ladderproblems};