ladderproblems =[
    {serial_no : 1,  problem_name : 'Queue at the School', contest_id:'266', problem_level : 'B'} ,
    {serial_no : 2,  problem_name : 'Xenia and Ringroad', contest_id:'339', problem_level : 'B'} ,
    {serial_no : 3,  problem_name : 'Fedor and New Game', contest_id:'467', problem_level : 'B'} ,
    {serial_no : 4,  problem_name : 'Random Teams', contest_id:'478', problem_level :  'B'},
    {serial_no : 5,  problem_name : 'Vanya and Lanterns', contest_id : '492', problem_level :  'B'},
    {serial_no : 6,  problem_name : 'Sort the Array', contest_id :'451', problem_level :  'B'} ,
    {serial_no : 7,  problem_name : 'Lecture',  contest_id :'499',problem_level : 'B'} ,
    {serial_no : 8,  problem_name : 'T-primes',contest_id : '230', problem_level : 'B'} ,
    {serial_no : 9,  problem_name : 'Anton and currency you all know', contest_id :'508', problem_level :  'B'} ,
    {serial_no : 10, problem_name :  'DZY Loves Strings', contest_id :'447', problem_level :  'B'} ,
    {serial_no : 11, problem_name :  'Amr and Pins', contest_id :'507', problem_level :  'B'} ,
    {serial_no : 12, problem_name :  'Little Pony and Sort by Shift',contest_id : '454', problem_level :  'B'} ,
    {serial_no : 13, problem_name :  'Jzzhu and Sequences', contest_id :'450', problem_level :  'B'} ,
    {serial_no : 14, problem_name :  'Roadside Trees (Simplified Edition)',contest_id : '265', problem_level :  'B'} ,
    {serial_no : 15, problem_name :  'Find Marble', contest_id :'285', problem_level :  'B'} ,
    {serial_no : 16, problem_name :  'Suffix Structures',contest_id : '448', problem_level :  'B'} ,
    {serial_no : 17, problem_name :  'Little Elephant and Magic Square', contest_id :'259', problem_level :  'B'} ,
    {serial_no : 18, problem_name :  'OR in Matrix', contest_id :'486', problem_level :  'B'} ,
    {serial_no : 19, problem_name :  'Football Kit',contest_id : '432', problem_level :  'B'} ,
    {serial_no : 20, problem_name :  'Little Girl and Game',contest_id : '276', problem_level :  'B'} ,
    {serial_no : 21, problem_name :  'Petya and Staircases',contest_id : '362', problem_level :  'B'} ,
    {serial_no : 22, problem_name :  'Books', contest_id :'279', problem_level :  'B'} ,
    {serial_no : 23, problem_name :  'Chat Online', contest_id :'469', problem_level :  'B'} ,
    {serial_no : 24, problem_name :  'Painting Pebbles', contest_id :'509', problem_level :  'B'} ,
    {serial_no : 25, problem_name :  'Vasya and Wrestling', contest_id :'493', problem_level :  'B'} ,
    {serial_no : 26, problem_name :  'George and Round',contest_id :'387', problem_level :  'B'} ,
    {serial_no : 27, problem_name :  'The Fibonacci Segment', contest_id :'365', problem_level :  'B'} ,
    {serial_no : 28, problem_name :  'Trace', contest_id :'157', problem_level :  'B'} ,
    {serial_no : 29, problem_name :  'Sale', contest_id :'34', problem_level :  'B'} ,
    {serial_no : 30, problem_name :  'Road Construction', contest_id :'330', problem_level :  'B'} ,
    {serial_no : 31, problem_name :  'Little Pigs and Wolves',contest_id : '116', problem_level :  'B'} ,
    {serial_no : 32, problem_name :  'Before an Exam',contest_id : '4', problem_level :  'B'} ,
    {serial_no : 33, problem_name :  'Painting Eggs', contest_id :'282', problem_level :  'B'} ,
    {serial_no : 34, problem_name :  'Lucky Substring', contest_id :'122', problem_level :  'B'} ,
    {serial_no : 35, problem_name :  'Combination', contest_id :'155', problem_level :  'B'} ,
    {serial_no : 36, problem_name :  'Jeff and Periods',contest_id : '352', problem_level :  'B'} ,
    {serial_no : 37, problem_name :  'Unary', contest_id :'133', problem_level :  'B'} ,
    {serial_no : 38, problem_name :  'Polo the Penguin and Matrix',contest_id : '289', problem_level :  'B'} ,
    {serial_no : 39, problem_name :  'Dima and To-do List',contest_id : '366', problem_level :  'B'} ,
    {serial_no : 40, problem_name :  'Coins', contest_id :'58', problem_level :  'B'} ,
    {serial_no : 41, problem_name :  'Han Solo and Lazer Gun', contest_id :'514', problem_level :  'B'} ,
    {serial_no : 42, problem_name :  'Garland', contest_id :'408', problem_level :  'B'} ,
    {serial_no : 43, problem_name :  'Flag Day', contest_id :'357', problem_level :  'B'} ,
    {serial_no : 44, problem_name :  'Art Union', contest_id :'416', problem_level :  'B'} ,
    {serial_no : 45, problem_name :  'Lucky String',contest_id : '110', problem_level :  'B'} ,
    {serial_no : 46, problem_name :  'Petya and Countryside',contest_id : '66', problem_level :  'B'} ,
    {serial_no : 47, problem_name :  'Archer', contest_id :'312', problem_level :  'B'} ,
    {serial_no : 48, problem_name :  'Routine Problem', contest_id :'337', problem_level :  'B'} ,
    {serial_no : 49, problem_name :  'Color the Fence', contest_id :'349', problem_level :  'B'} ,
    {serial_no : 50, problem_name :  'Levko and Permutation', contest_id :'361', problem_level :  'B'} ,
    {serial_no : 51, problem_name :  "Vasya's Calendar", contest_id :'182', problem_level :  'B'} ,
    {serial_no : 52, problem_name :  'Reading', contest_id :'234', problem_level :  'B'} ,
    {serial_no : 53, problem_name :  'Phone Numbers', contest_id :'151', problem_level :  'B'} ,
    {serial_no : 54, problem_name :  'Permutation', contest_id :'359', problem_level :  'B'} ,
    {serial_no : 55, problem_name :  'Students and Shoelaces', contest_id :'129', problem_level :  'B'} ,
    {serial_no : 56, problem_name :  'Help Kingdom of Far Far Away 2',contest_id : '143', problem_level :  'B'} ,
    {serial_no : 57, problem_name :  'The Child and Set', contest_id :'437', problem_level :  'B'} ,
    {serial_no : 58, problem_name :  'Non-square Equation', contest_id :'233', problem_level :  'B'} ,
    {serial_no : 59, problem_name :  'Special Offer! Super Price 999 Bourles!', contest_id :'219', problem_level :  'B'} ,
    {serial_no : 60, problem_name :  'Little Elephant and Sorting', contest_id :'205', problem_level :  'B'} ,
    {serial_no : 61, problem_name :  'Walking in the Rain', contest_id :'192', problem_level :  'B'} ,
    {serial_no : 62, problem_name :  'Two Tables', contest_id :'228', problem_level :  'B'} ,
    {serial_no : 63, problem_name :  'Xenia and Spies',contest_id : '342', problem_level :  'B'} ,
    {serial_no : 64, problem_name :  'Lucky Numbers (easy)',contest_id : '96', problem_level :  'B'} ,
    {serial_no : 65, problem_name :  'Ping-Pong (Easy Version)', contest_id :'320', problem_level :  'B'} ,
    {serial_no : 66, problem_name :  'After Training', contest_id :'195', problem_level :  'B'} ,
    {serial_no : 67, problem_name :  'Magic, Wizardry and Wonders', contest_id :'231', problem_level :  'B'} ,
    {serial_no : 68, problem_name :  'Limit', contest_id :'197', problem_level :  'B'} ,
    {serial_no : 69, problem_name :  'Ancient Prophesy',contest_id : '260', problem_level :  'B'} ,
    {serial_no : 70, problem_name :  'Hometask', contest_id :'214', problem_level :  'B'} ,
    {serial_no : 71, problem_name :  'Well-known Numbers',contest_id : '225', problem_level :  'B'} ,
    {serial_no : 72, problem_name :  "Settlers' Training",contest_id : '63', problem_level :  'B'} ,
    {serial_no : 73, problem_name :  'Nearest Fraction',contest_id : '281', problem_level :  'B'} ,
    {serial_no : 74, problem_name :  'Counting Rhombi', contest_id :'189', problem_level :  'B'} ,
    {serial_no : 75, problem_name :  'Friends', contest_id :'94', problem_level :  'B'} ,
    {serial_no : 76, problem_name :  'Undoubtedly Lucky Numbers', contest_id :'244', problem_level :  'B'} ,
    {serial_no : 77, problem_name :  'Forming Teams', contest_id :'216', problem_level :  'B'} ,
    {serial_no : 78, problem_name :  'Inna and Nine', contest_id :'374', problem_level :  'B'} ,
    {serial_no : 79, problem_name :  'Bets', contest_id :'69', problem_level :  'B'} ,
    {serial_no : 80, problem_name :  'Young Photographer',contest_id : '14', problem_level :  'B'} ,
    {serial_no : 81, problem_name :  'Martian Clock',contest_id : '149', problem_level :  'B'} ,
    {serial_no : 82, problem_name :  'Jury Size', contest_id :'254', problem_level :  'B'} ,
    {serial_no : 83, problem_name :  'Hard Work', contest_id :'61', problem_level :  'B'} ,
    {serial_no : 84, problem_name :  'Testing Pants for Sadness', contest_id :'103',problem_level : 'A'} ,
    {serial_no : 85, problem_name :  'Running Student', contest_id :'9', problem_level :  'B'} ,
    {serial_no : 86, problem_name :  'Tournament', contest_id :'27', problem_level :  'B'} ,
    {serial_no : 87, problem_name :  'Magical Array', contest_id :'83', problem_level :'A'} ,
    {serial_no : 88, problem_name :  'Help Chef Gerasim',contest_id : '99', problem_level :  'B'} ,
    {serial_no : 89, problem_name :  'Convex Shape', contest_id :'275', problem_level :  'B'} ,
    {serial_no : 90, problem_name :  'Surrounded', contest_id :'190', problem_level :  'B'} ,
    {serial_no : 91, problem_name :  'Spoilt Permutation', contest_id :'56', problem_level :  'B'} ,
    {serial_no : 92, problem_name :  'PFAST Inc.',contest_id : '114', problem_level :  'B'} ,
    {serial_no : 93, problem_name :  'Martian Dollar', contest_id :'41', problem_level :  'B'} ,
    {serial_no : 94, problem_name :  'Bargaining Table', contest_id :'22', problem_level :  'B'} ,
    {serial_no : 95, problem_name :  'Sysadmin Bob', contest_id :'31', problem_level :  'B'} ,
    {serial_no : 96, problem_name :  'Facetook Priority Wall', contest_id :'75', problem_level :  'B'} ,
    {serial_no : 97, problem_name :  'Maximal Area Quadrilateral',contest_id : '340', problem_level :  'B'} ,
    {serial_no : 98, problem_name :  'Traffic Lights',contest_id : '29', problem_level :  'B'} ,
    {serial_no : 99, problem_name :  'Blog Photo', contest_id :'53', problem_level :  'B'} ,
    {serial_no : 100, problem_name : 'Three matrices',contest_id : '393', problem_level :  'B'} ,
]
 

module.exports = {ladderproblems}