ladderproblems = [
    {serial_no: 1,  problem_name :'Arrival of the General',  contest_id :'144', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Beautiful Matrix', contest_id : '263', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Ultra-Fast Mathematician',  contest_id :'61', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Blackjack',  contest_id :'104', problem_level :  'A' },
    {serial_no: 5,  problem_name :'HQ9+',  contest_id :'133', problem_level :  'A' },
    {serial_no: 6,  problem_name :'I_love_username',  contest_id :'155', problem_level :  'A' },
    {serial_no: 7,  problem_name :'Petya and Strings',  contest_id :'112', problem_level :  'A' },
    {serial_no: 8,  problem_name :'Cookies',  contest_id :'129', problem_level :  'A' },
    {serial_no: 9,  problem_name :'Candy Bags', contest_id : '334', problem_level :  'A' },
    {serial_no: 10, problem_name : 'Drinks',  contest_id :'200', problem_level :  'B' },
    {serial_no: 11, problem_name : 'Vasily the Bear and Triangle', contest_id : '336', problem_level :  'A' },
    {serial_no: 12, problem_name : 'Lunch Rush',  contest_id :'276', problem_level :  'A' },
    {serial_no: 13, problem_name : 'Cakeminator', contest_id : '330', problem_level :  'A' },
    {serial_no: 14, problem_name : 'Stones on the Table',  contest_id :'266', problem_level :  'A' },
    {serial_no: 15, problem_name : 'Bit++', contest_id : '282', problem_level :  'A' },
    {serial_no: 16, problem_name : 'Levko and Table',  contest_id :'361', problem_level :  'A' },
    {serial_no: 17, problem_name : 'Young Physicist', contest_id : '69', problem_level :  'A' },
    {serial_no: 18, problem_name : 'Chips', contest_id : '92', problem_level :  'A' },
    {serial_no: 19, problem_name : 'Tram', contest_id : '116', problem_level :  'A' },
    {serial_no: 20, problem_name : 'Queue at the School', contest_id : '266', problem_level :  'B' },
    {serial_no: 21, problem_name : 'Way Too Long Words', contest_id : '71', problem_level :  'A' },
    {serial_no: 22, problem_name : 'Present from Lena', contest_id : '118', problem_level :  'B' },
    {serial_no: 23, problem_name : 'Jeff and Digits', contest_id : '352', problem_level :  'A' },
    {serial_no: 24, problem_name : 'Slightly Decreasing Permutations', contest_id : '285', problem_level :  'A' },
    {serial_no: 25, problem_name : 'Sale', contest_id : '34', problem_level :  'B' },
    {serial_no: 26, problem_name : 'Fancy Fence',  contest_id :'270', problem_level :  'A' },
    {serial_no: 27, problem_name : 'Dragons', contest_id : '230', problem_level :  'A' },
    {serial_no: 28, problem_name : 'The number of positions', contest_id : '124', problem_level :  'A' },
    {serial_no: 29, problem_name : 'Translation', contest_id :'41', problem_level :  'A' },
    {serial_no: 30, problem_name : 'Wizards and Demonstration',  contest_id :'168', problem_level :  'A' },
    {serial_no: 31, problem_name : 'Xenia and Ringroad', contest_id : '339', problem_level :  'B' },
    {serial_no: 32, problem_name : 'Little Elephant and Rozdil', contest_id : '205', problem_level :  'A' },
    {serial_no: 33, problem_name : 'Life Without Zeros', contest_id : '75', problem_level :  'A' },
    {serial_no: 34, problem_name : 'Football', contest_id : '43', problem_level :  'A' },
    {serial_no: 35, problem_name : 'Dubstep',  contest_id :'208', problem_level :  'A' },
    {serial_no: 36, problem_name : 'Magic Numbers', contest_id : '320', problem_level :  'A' },
    {serial_no: 37, problem_name : 'String Task', contest_id : '118', problem_level :  'A' },
    {serial_no: 38, problem_name : 'Lucky Division',  contest_id :'122', problem_level :  'A' },
    {serial_no: 39, problem_name : 'Array', contest_id : '300', problem_level :  'A' },
    {serial_no: 40, problem_name : 'Sum of Digits',  contest_id :'102', problem_level :  'B' },
    {serial_no: 41, problem_name : 'k-String',  contest_id :'219', problem_level :  'A' },
    {serial_no: 42, problem_name : 'Puzzles',  contest_id :'337', problem_level :  'A' },
    {serial_no: 43, problem_name : 'Next Test', contest_id : '27', problem_level :  'A' },
    {serial_no: 44, problem_name : 'Laptops',  contest_id :'456', problem_level :  'A' },
    {serial_no: 45, problem_name : 'Pashmak and Garden',  contest_id :'459', problem_level :  'A' },
    {serial_no: 46, problem_name : 'Lucky Sum', contest_id : '121', problem_level :  'A' },
    {serial_no: 47, problem_name : "Kuriyama Mirai's Stones",  contest_id :'433', problem_level :  'B' },
    {serial_no: 48, problem_name : "Kitahara Haruki's Gift", contest_id : '433', problem_level :  'A' },
    {serial_no: 49, problem_name : 'The Fibonacci Segment', contest_id : '365', problem_level :  'B' },
    {serial_no: 50, problem_name : 'Difference Row', contest_id : '347', problem_level :  'A' },
    {serial_no: 51, problem_name : 'Little Pigs and Wolves', contest_id : '116', problem_level :  'B' },
    {serial_no: 52, problem_name : 'T-primes', contest_id : '230', problem_level :  'B' },
    {serial_no: 53, problem_name : 'Xenia and Divisors',  contest_id :'342', problem_level :  'A' },
    {serial_no: 54, problem_name : 'Learning Languages',  contest_id :'277', problem_level :  'A' },
    {serial_no: 55, problem_name : 'The Child and Toy',  contest_id :'437', problem_level :  'C' },
    {serial_no: 56, problem_name : 'Sail', contest_id : '298', problem_level :  'B' },
    {serial_no: 57, problem_name : 'Find Marble',  contest_id :'285', problem_level :  'B' },
    {serial_no: 58, problem_name : 'Free Cash', contest_id : '237', problem_level :  'A' },
    {serial_no: 59, problem_name : 'Roma and Changing Signs', contest_id : '262', problem_level :  'B' },
    {serial_no: 60, problem_name : 'Dreamoon and WiFi',  contest_id :'476', problem_level :  'B' },
    {serial_no: 61, problem_name : 'Dima and Staircase',  contest_id :'272', problem_level :  'C' },
    {serial_no: 62, problem_name : 'Comparing Strings', contest_id : '186', problem_level :  'A' },
    {serial_no: 63, problem_name : 'Sereja and Array', contest_id : '315', problem_level :  'B' },
    {serial_no: 64, problem_name : 'Sereja and Suffixes',  contest_id :'368', problem_level :  'B' },
    {serial_no: 65, problem_name : 'Pashmak and Flowers',  contest_id :'459', problem_level :  'B' },
    {serial_no: 66, problem_name : 'Simple Molecules', contest_id : '344', problem_level :  'B' },
    {serial_no: 67, problem_name : 'DZY Loves Chessboard', contest_id : '445', problem_level :  'A' },
    {serial_no: 68, problem_name : 'Fixed Points',  contest_id :'347', problem_level :  'B' },
    {serial_no: 69, problem_name : 'Hungry Sequence', contest_id : '327', problem_level :  'B' },
    {serial_no: 70, problem_name : 'Building Permutation', contest_id : '285', problem_level :  'C' },
    {serial_no: 71, problem_name : 'Road Construction',  contest_id :'330', problem_level :  'B' },
    {serial_no: 72, problem_name : 'Little Girl and Game',  contest_id :'276', problem_level :  'B' },
    {serial_no: 73, problem_name : 'Fence',  contest_id :'363', problem_level :  'B' },
    {serial_no: 74, problem_name : 'Flipping Game', contest_id : '327', problem_level :  'A' },
    {serial_no: 75, problem_name : 'Cut Ribbon', contest_id : '189', problem_level :  'A' },
    {serial_no: 76, problem_name : 'Ilya and Queries', contest_id : '313', problem_level :  'B' },
    {serial_no: 77, problem_name : 'Little Dima and Equation',  contest_id :'460', problem_level :  'B' },
    {serial_no: 78, problem_name : 'George and Job',  contest_id :'467', problem_level :  'C' },
    {serial_no: 79, problem_name : 'Sereja and Bottles',  contest_id :'315', problem_level :  'A' },
    {serial_no: 80, problem_name : 'Routine Problem',  contest_id :'337', problem_level :  'B' },
    {serial_no: 81, problem_name : 'Hamburgers', contest_id : '371', problem_level :  'C' },
    {serial_no: 82, problem_name : 'Jzzhu and Sequences',  contest_id :'450', problem_level :  'B' },
    {serial_no: 83, problem_name : 'Flag Day', contest_id : '357', problem_level :  'B' },
    {serial_no: 84, problem_name : 'Valera and Fruits',  contest_id :'441', problem_level :  'B' },
    {serial_no: 85, problem_name : 'Fox Dividing Cheese',  contest_id :'371', problem_level :  'B' },
    {serial_no: 86, problem_name : 'Dima and Continuous Line',  contest_id :'358', problem_level :  'A' },
    {serial_no: 87, problem_name : 'Lucky Numbers (easy)',  contest_id :'96', problem_level :  'B' },
    {serial_no: 88, problem_name : 'Coach',  contest_id :'300', problem_level :  'B' },
    {serial_no: 89, problem_name : 'Ciel and Flowers', contest_id : '322', problem_level :  'B' },
    {serial_no: 90, problem_name : 'k-Tree',  contest_id :'431', problem_level :  'C' },
    {serial_no: 91, problem_name : 'Maximum Absurdity', contest_id : '332', problem_level :  'B' },
    {serial_no: 92, problem_name : 'Fixing Typos',  contest_id :'363', problem_level :  'C' },
    {serial_no: 93, problem_name : 'Exams',  contest_id :'479', problem_level :  'C' },
    {serial_no: 94, problem_name : 'Boredom',  contest_id :'455', problem_level :  'A' },
    {serial_no: 95, problem_name : 'Prime Matrix',  contest_id :'271', problem_level :  'B' },
    {serial_no: 96, problem_name : 'Books', contest_id : '279', problem_level :  'B' },
    {serial_no: 97, problem_name : 'Little Girl and Maximum Sum',  contest_id :'276', problem_level :  'C' },
    {serial_no: 98, problem_name : 'Tetrahedron',  contest_id :'166', problem_level :  'E' },
    {serial_no: 99, problem_name : 'XOR and OR',  contest_id :'282', problem_level :  'C' },
    {serial_no: 100, problem_name : 'Painting Eggs',  contest_id :'282', problem_level :  'B' }
]

module.exports = {ladderproblems}