ladderproblems = [
    {serial_no: 1, problem_name :  'Fox And Snake',  contest_id :'510', problem_level : 'A' },
    {serial_no: 2, problem_name : 'Pangram', contest_id : '520', problem_level : 'A' },
    {serial_no: 3, problem_name : 'Vanya and Cubes',  contest_id :'492', problem_level : 'A' },
    {serial_no: 4, problem_name : 'Minimum Difficulty', contest_id : '496', problem_level : 'A' },
    {serial_no: 5, problem_name : 'Dreamoon and WiFi',  contest_id :'476', problem_level : 'B' },
    {serial_no: 6, problem_name : 'Giga Tower', contest_id : '488', problem_level : 'A' },
    {serial_no: 7, problem_name : 'Vanya and Lanterns',  contest_id :'492', problem_level : 'B' },
    {serial_no: 8, problem_name : 'Two Buttons',  contest_id :'520',  problem_level : 'B' },
    {serial_no: 9, problem_name : 'Good Sequences', contest_id : '264', problem_level : 'B' },
    {serial_no: 10, problem_name : 'Long Path', contest_id : '407',  problem_level : 'B' },
    {serial_no: 11, problem_name : 'Maximum Submatrix 2', contest_id : '375', problem_level : 'B' },
    {serial_no: 12, problem_name : 'Glass Carving', contest_id : '527', problem_level :  'D' },
    {serial_no: 13, problem_name : 'Factory', contest_id : '485', problem_level : 'A' },
    {serial_no: 14, problem_name : 'Mr. Kitayuta, the Treasure Hunter', contest_id : '505',  problem_level : 'D' },
    {serial_no: 15, problem_name : 'Number of Ways', contest_id : '466', problem_level : 'D' },
    {serial_no: 16, problem_name : 'Vanya and Exams', contest_id : '492', problem_level : 'D' },
    {serial_no: 17, problem_name : 'Clique Problem', contest_id : '527', problem_level : 'D' },
    {serial_no: 18, problem_name : 'Triangle', contest_id : '407', problem_level : 'A' },
    {serial_no: 19, problem_name : 'DZY Loves Sequences', contest_id : '446', problem_level : 'A' },
    {serial_no: 20, problem_name : 'Boredom', contest_id : '455', problem_level : 'A' },
    {serial_no: 21, problem_name : 'Fox and Card Game',  contest_id :'388', problem_level : 'D' },
    {serial_no: 22, problem_name : 'Fox and Minimal path', contest_id : '388', problem_level : 'B' },
    {serial_no: 23, problem_name : 'Drazil and Tiles', contest_id : '515', problem_level : 'D' },
    {serial_no: 24, problem_name : 'Vanya and Field', contest_id : '492', problem_level : 'E' },
    {serial_no: 25, problem_name : 'Watching Fireworks is Fun', contest_id : '372', problem_level :  'D' },
    {serial_no: 26, problem_name : 'Sereja and Table ', contest_id : '425', problem_level : 'B' },
    {serial_no: 27, problem_name : 'Ciel and Duel', contest_id : '321', problem_level : 'B' },
    {serial_no: 28, problem_name : 'Three States',  contest_id :'590',  problem_level : 'D' },
    {serial_no: 29, problem_name : 'Little Pony and Harmony Chest',  contest_id :'453', problem_level : 'B' },
    {serial_no: 30, problem_name : 'Increase Sequence', contest_id : '466', problem_level : 'D' },
    {serial_no: 31, problem_name : "Pashmak and Parmida's problem", contest_id : '459', problem_level : 'D' },
    {serial_no: 32, problem_name : 'Levko and Array', contest_id : '360', problem_level : 'B' },
    {serial_no: 33, problem_name : 'Vanya and Computer Game', contest_id : '492', problem_level : 'D' },
    {serial_no: 34, problem_name : 'Appleman and a Sheet of Paper', contest_id : '461', problem_level : 'D' },
    {serial_no: 35, problem_name : 'Jeff and Permutation', contest_id : '351', problem_level : 'E' },
    {serial_no: 36, problem_name : 'Ciel the Commander',  contest_id :'321',  problem_level : 'D' },
    {serial_no: 37, problem_name : 'Pair of Numbers',  contest_id :'359', problem_level : 'D' },
    {serial_no: 38, problem_name : 'Wonder Room',  contest_id :'466', problem_level : 'B' },
    {serial_no: 39, problem_name : 'Upgrading Array',  contest_id :'402',problem_level : 'D' },
    {serial_no: 40, problem_name : 'Pashmak and Graph', contest_id : '459',problem_level :  'E' },
    {serial_no: 41, problem_name : 'DZY Loves Modification', contest_id : '446', problem_level : 'B' },
    {serial_no: 42, problem_name : 'Water Tree', contest_id : '343', problem_level : 'D' },
    {serial_no: 43, problem_name : 'Appleman and Tree', contest_id : '461', problem_level : 'B' },
    {serial_no: 44, problem_name : 'Gerald and Giant Chess', contest_id : '559', problem_level :  'D' },
    {serial_no: 45, problem_name : 'Array and Operations',  contest_id :'498', problem_level :  'D' },
    {serial_no: 46, problem_name : 'Restore Cube ', contest_id : '464', problem_level : 'B' },
    {serial_no: 47, problem_name : 'Lucky Subsequence', contest_id : '145', problem_level :  'D' },
    {serial_no: 48, problem_name : 'Little Elephant and Array', contest_id : '220', problem_level : 'B' },
    {serial_no: 49, problem_name : 'Strip', contest_id : '487', problem_level : 'B' },
    {serial_no: 50, problem_name : 'Sereja and Brackets',  contest_id :'380', problem_level : 'D' },
    {serial_no: 51, problem_name : 'Mashmokh and Reverse Operation', contest_id : '414', problem_level : 'D' },
    {serial_no: 52, problem_name : 'Prefixes and Suffixes', contest_id : '432', problem_level : 'D' },
    {serial_no: 53, problem_name : 'Propagating tree', contest_id : '383', problem_level :  'D' },
    {serial_no: 54, problem_name : 'Two Sets',  contest_id :'468', problem_level : 'B' },
    {serial_no: 55, problem_name : 'Civilization',  contest_id :'455', problem_level : 'D' },
    {serial_no: 56, problem_name : 'Little Pony and Summer Sun Celebration',  contest_id :'453', problem_level : 'D' },
    {serial_no: 57, problem_name : 'Watto and Mechanism',  contest_id :'514', problem_level : 'D' },
    {serial_no: 58, problem_name : 'Substitutes in Number', contest_id : '464', problem_level : 'D' },
    {serial_no: 59, problem_name : 'A Lot of Games', contest_id : '455', problem_level : 'B' },
    {serial_no: 60, problem_name : 'Jzzhu and Cities', contest_id : '449', problem_level : 'B' },
    {serial_no: 61, problem_name : 'Caisa and Tree', contest_id : '463', problem_level : 'E' },
    {serial_no: 62, problem_name : 'Hill Climbing',  contest_id :'406', problem_level : 'D' },
    {serial_no: 63, problem_name : "Mr. Kitayuta's Colorful Graph", contest_id : '506', problem_level : 'D' },
    {serial_no: 64, problem_name : 'Double Profiles',  contest_id :'154', problem_level : 'D' },
    {serial_no: 65, problem_name : 'Number Transformation II',  contest_id :'346', problem_level : 'D' },
    {serial_no: 66, problem_name : 'Darth Vader and Tree',  contest_id :'514', problem_level : 'E' },
    {serial_no: 67, problem_name : 'Divisors',  contest_id :'448', problem_level : 'E' },
    {serial_no: 68, problem_name : 'Captains Mode',  contest_id :'377', problem_level : 'D' },
    {serial_no: 69, problem_name : 'Mike and Frog', contest_id : '547', problem_level : 'A' },
    {serial_no: 70, problem_name : 'Sereja and Two Sequences',  contest_id :'425', problem_level :  'D' },
    {serial_no: 71, problem_name : 'A Simple Task', contest_id : '558', problem_level : 'E' },
    {serial_no: 72, problem_name : 'Devu and Birthday Celebration', contest_id : '439', problem_level : 'E' },
    {serial_no: 73, problem_name : 'Sereja and Squares', contest_id : '425', problem_level : 'D' },
    {serial_no: 74, problem_name : 'Traffic Jams in the Land',  contest_id :'498', problem_level : 'D' },
    {serial_no: 75, problem_name : 'Match & Catch',  contest_id :'427', problem_level : 'D' },
    {serial_no: 76, problem_name : 'DZY Loves FFT',  contest_id :'444', problem_level : 'B' },
    {serial_no: 77, problem_name : 'The Child and Sequence', contest_id : '438', problem_level : 'D' },
    {serial_no: 78, problem_name : 'Vasya and Beautiful Arrays', contest_id : '354', problem_level : 'D' },
    {serial_no: 79, problem_name : 'Beautiful Pairs of Numbers', contest_id : '403', problem_level : 'D' },
    {serial_no: 80, problem_name : 'Tricky Function',  contest_id :'429', problem_level : 'D' },
    {serial_no: 81, problem_name : 'Antimatter',  contest_id :'383', problem_level : 'D' },
    {serial_no: 82, problem_name : 'DZY Loves Colors',  contest_id :'444', problem_level : 'D' },
    {serial_no: 83, problem_name : 'Information Graph', contest_id : '466', problem_level : 'E' },
    {serial_no: 84, problem_name : 'Jzzhu and Numbers', contest_id : '449', problem_level : 'D' },
    {serial_no: 85, problem_name : 'Little Elephant and Inversions', contest_id : '220', problem_level : 'E' },
    {serial_no: 86, problem_name : 'Subset Sums', contest_id : '348', problem_level :  'D' },
    {serial_no: 87, problem_name : 'Arthur and Walls', contest_id : '525', problem_level : 'D' },
    {serial_no: 88, problem_name : 'Mashmokh and Water Tanks', contest_id : '414', problem_level : 'D' },
    {serial_no: 89, problem_name : 'Square Tiling', contest_id : '432', problem_level : 'E' },
    {serial_no: 90, problem_name : 'Alex and Complicated Task',  contest_id :'467', problem_level : 'E' },
    {serial_no: 91, problem_name : 'Fedor and Essay',  contest_id :'467', problem_level : 'D' },
    {serial_no: 92, problem_name : 'Case of a Top Secret',  contest_id :'555', problem_level : 'D' },
    {serial_no: 93, problem_name : 'Xenia and Tree',  contest_id :'342', problem_level : 'E' },
    {serial_no: 94, problem_name : 'Kindergarten',  contest_id :'484', problem_level : 'D' },
    {serial_no: 95, problem_name : 'Artem and Array ', contest_id : '442', problem_level :  'D' },
    {serial_no: 96, problem_name : 'Jzzhu and Apples',  contest_id :'449', problem_level : 'D' },
    {serial_no: 97, problem_name : 'DZY Loves Fibonacci Numbers', contest_id : '446', problem_level : 'D' },
    {serial_no: 98, problem_name : 'Polo the Penguin and Trees ', contest_id : '288', problem_level : 'D' },
    {serial_no: 99, problem_name : 'Sign on Fence', contest_id : '484', problem_level : 'E' },
    {serial_no: 100, problem_name : 'Serega and Fun',  contest_id :'455', problem_level : 'D' }
]


module.exports ={ladderproblems}
