  
ladderproblems = [
    {serial_no: 1,  problem_name :'Choosing Teams', contest_id : '432', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Nearly Lucky Number', contest_id : '110', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Amusing Joke',  contest_id :'141', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Drinks', contest_id : '200', problem_level :  'B' },
    {serial_no: 5,  problem_name :'Way Too Long Words', contest_id : '71', problem_level :  'A' },
    {serial_no: 6,  problem_name :'Presents',  contest_id :'136', problem_level :  'A' },
    {serial_no: 7,  problem_name :'Lunch Rush',  contest_id :'276', problem_level :  'A' },
    {serial_no: 8,  problem_name :'Soft Drinking', contest_id : '151', problem_level :  'A' },
    {serial_no: 9,  problem_name :'Boy or Girl', contest_id : '236', problem_level :  'A' },
    {serial_no: 10, problem_name : 'Dividing Orange', contest_id : '244', problem_level :  'A' },
    {serial_no: 11, problem_name : 'Queue at the School',  contest_id :'266', problem_level :  'B' },
    {serial_no: 12, problem_name : 'HQ9+',  contest_id :'133', problem_level :  'A' },
    {serial_no: 13, problem_name : 'I_love_username',  contest_id :'155', problem_level :  'A' },
    {serial_no: 14, problem_name : 'Cakeminator', contest_id : '330', problem_level :  'A' },
    {serial_no: 15, problem_name : 'Word',  contest_id :'59', problem_level :  'A' },
    {serial_no: 16, problem_name : 'Stones on the Table',  contest_id :'266', problem_level :  'A' },
    {serial_no: 17, problem_name : 'Beautiful Year',  contest_id :'271', problem_level :  'A' },
    {serial_no: 18, problem_name : 'Team', contest_id : '231', problem_level :  'A' },
    {serial_no: 19, problem_name : 'Insomnia cure', contest_id : '148', problem_level :  'A' },
    {serial_no: 20, problem_name : 'Vanya and Cards',  contest_id :'401', problem_level :  'A' },
    {serial_no: 21, problem_name : 'Tram', contest_id : '116', problem_level :  'A' },
    {serial_no: 22, problem_name : 'Petya and Strings',  contest_id :'112', problem_level :  'A' },
    {serial_no: 23, problem_name : 'Array', contest_id : '300', problem_level :  'A' },
    {serial_no: 24, problem_name : 'Little Elephant and Chess', contest_id : '259', problem_level :  'A' },
    {serial_no: 25, problem_name : 'Dubstep', contest_id : '208', problem_level :  'A' },
    {serial_no: 26, problem_name : 'Permutation', contest_id : '137', problem_level :  'B' },
    {serial_no: 27, problem_name : 'Magic Numbers',  contest_id :'320', problem_level :  'A' },
    {serial_no: 28, problem_name : 'Heads or Tails', contest_id : '242', problem_level :  'A' },
    {serial_no: 29, problem_name : 'Present from Lena', contest_id : '118', problem_level :  'B' },
    {serial_no: 30, problem_name : 'Marks', contest_id : '152', problem_level :  'A' },
    {serial_no: 31, problem_name : 'Xenia and Ringroad',  contest_id :'339', problem_level :  'B' },
    {serial_no: 32, problem_name : 'Lucky Division', contest_id : '122', problem_level :  'A' },
    {serial_no: 33, problem_name : 'Twins',  contest_id :'160', problem_level :  'A' },
    {serial_no: 34, problem_name : 'Translation',  contest_id :'41', problem_level :  'A' },
    {serial_no: 35, problem_name : 'Chat room', contest_id : '58', problem_level :  'A' },
    {serial_no: 36, problem_name : 'Football', contest_id : '96', problem_level :  'A' },
    {serial_no: 37, problem_name : 'Ilya and Bank Account', contest_id : '313', problem_level :  'A' },
    {serial_no: 38, problem_name : 'Parallelepiped',  contest_id :'224', problem_level :  'A' },
    {serial_no: 39, problem_name : 'String Task', contest_id :'118', problem_level :  'A' },
    {serial_no: 40, problem_name : 'k-String',  contest_id :'219', problem_level :  'A' },
    {serial_no: 41, problem_name : 'Dragons', contest_id : '230', problem_level :  'A' },
    {serial_no: 42, problem_name : 'Puzzles', contest_id : '337', problem_level :  'A' },
    {serial_no: 43, problem_name : 'Playing Cubes',  contest_id :'257', problem_level :  'B' },
    {serial_no: 44, problem_name : 'Two Bags of Potatoes',  contest_id :'239', problem_level :  'A' },
    {serial_no: 45, problem_name : 'Big Segment',  contest_id :'242', problem_level :  'B' },
    {serial_no: 46, problem_name : 'Pashmak and Flowers',  contest_id :'459', problem_level :  'B' },
    {serial_no: 47, problem_name : 'Building Permutation', contest_id : '285', problem_level :  'C' },
    {serial_no: 48, problem_name : 'Boys and Girls',  contest_id :'253', problem_level :  'A' },
    {serial_no: 49, problem_name : 'Cinema Line', contest_id : '349', problem_level :  'A' },
    {serial_no: 50, problem_name : 'Rank List',  contest_id :'166', problem_level :  'A' },
    {serial_no: 51, problem_name : 'Points on Line',  contest_id :'251', problem_level :  'A' },
    {serial_no: 52, problem_name : 'Little Girl and Game',  contest_id :'276', problem_level :  'B' },
    {serial_no: 53, problem_name : 'Little Pony and Expected Maximum', contest_id : '453', problem_level :  'A' },
    {serial_no: 54, problem_name : 'Cosmic Tables', contest_id : '222', problem_level :  'B' },
    {serial_no: 55, problem_name : 'Lucky Sum of Digits', contest_id : '109', problem_level :  'A' },
    {serial_no: 56, problem_name : 'Ice Skating',  contest_id :'217', problem_level :  'A' },
    {serial_no: 57, problem_name : 'Sereja and Suffixes', contest_id : '368', problem_level :  'B' },
    {serial_no: 58, problem_name : 'Free Cash',  contest_id :'237', problem_level :  'A' },
    {serial_no: 59, problem_name : 'Mashmokh and ACM', contest_id : '414', problem_level :  'B' },
    {serial_no: 60, problem_name : 'Domino',  contest_id :'353', problem_level :  'A' },
    {serial_no: 61, problem_name : 'Hungry Sequence', contest_id : '327', problem_level :  'B' },
    {serial_no: 62, problem_name : 'Ilya and Queries',  contest_id :'313', problem_level :  'B' },
    {serial_no: 63, problem_name : 'Fence',  contest_id :'363', problem_level :  'B' },
    {serial_no: 64, problem_name : 'T-primes',  contest_id :'230', problem_level :  'B' },
    {serial_no: 65, problem_name : 'Flipping Game',  contest_id :'327', problem_level :  'A' },
    {serial_no: 66, problem_name : 'Cut Ribbon', contest_id : '189', problem_level :  'A' },
    {serial_no: 67, problem_name : 'Counting Kangaroos is Fun', contest_id : '372', problem_level :  'A' },
    {serial_no: 68, problem_name : 'Median', contest_id : '166', problem_level :  'C' },
    {serial_no: 69, problem_name : 'Ciel and Flowers', contest_id : '322', problem_level :  'B' },
    {serial_no: 70, problem_name : 'Vanya and Exams', contest_id : '492', problem_level :  'C' },
    {serial_no: 71, problem_name : 'Fixing Typos',  contest_id :'363', problem_level :  'C' },
    {serial_no: 72, problem_name : 'LCM Challenge', contest_id : '235', problem_level :  'A' },
    {serial_no: 73, problem_name : "Caesar's Legions",  contest_id :'118', problem_level :  'D' },
    {serial_no: 74, problem_name : 'Xenia and Bit Operations', contest_id : '339', problem_level :  'D' },
    {serial_no: 75, problem_name : 'Little Girl and Maximum Sum', contest_id : '276', problem_level :  'C' },
    {serial_no: 76, problem_name : 'Palindrome Transformation', contest_id : '486', problem_level :  'C' },
    {serial_no: 77, problem_name : 'Array',  contest_id :'224', problem_level :  'B' },
    {serial_no: 78, problem_name : 'Factory',  contest_id :'485', problem_level :  'A' },
    {serial_no: 79, problem_name : 'Ping-Pong (Easy Version)', contest_id : '320', problem_level :  'B' },
    {serial_no: 80, problem_name : 'Routine Problem', contest_id : '337', problem_level :  'B' },
    {serial_no: 81, problem_name : 'Tourist Problem', contest_id : '340', problem_level :  'C' },
    {serial_no: 82, problem_name : 'Color Stripe',  contest_id :'219', problem_level :  'C' },
    {serial_no: 83, problem_name : 'Maze',  contest_id :'377', problem_level :  'A' },
    {serial_no: 84, problem_name : 'Valera and Tubes ', contest_id : '441', problem_level :  'C' },
    {serial_no: 85, problem_name : 'Polo the Penguin and Matrix', contest_id : '289', problem_level :  'B' },
    {serial_no: 86, problem_name : 'Boredom',  contest_id :'455', problem_level :  'A' },
    {serial_no: 87, problem_name : 'Funky Numbers',  contest_id :'192', problem_level :  'A' },
    {serial_no: 88, problem_name : 'George and Job',  contest_id :'467', problem_level :  'C' },
    {serial_no: 89, problem_name : 'Xenia and Weights',  contest_id :'339', problem_level :  'C' },
    {serial_no: 90, problem_name : 'Physics Practical', contest_id : '253', problem_level :  'B' },
    {serial_no: 91, problem_name : 'Little Pony and Sort by Shift', contest_id : '454', problem_level :  'B' },
    {serial_no: 92, problem_name : 'Bombs',  contest_id :'350', problem_level :  'C' },
    {serial_no: 93, problem_name : 'Number of Ways',  contest_id :'466', problem_level :  'C' },
    {serial_no: 94, problem_name : 'Team',  contest_id :'401', problem_level :  'C' },
    {serial_no: 95, problem_name : 'Another Problem on Strings', contest_id : '165', problem_level :  'C' },
    {serial_no: 96, problem_name : 'Color the Fence',  contest_id :'349', problem_level :  'B' },
    {serial_no: 97, problem_name : 'Tetrahedron', contest_id : '166', problem_level :  'E' },
    {serial_no: 98, problem_name : 'k-Tree', contest_id : '431', problem_level :  'C' },
    {serial_no: 99, problem_name : 'Vasya and Basketball',  contest_id :'493', problem_level :  'C' },
    {serial_no: 100, problem_name : 'Gargari and Bishops',  contest_id :'463', problem_level :  'C' }
]

module.exports = {ladderproblems};