ladderproblems = [
    {serial_no: 1,  problem_name :'Young Physicist', contest_id : '69', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Beautiful Matrix',  contest_id :'263', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Queue at the School',  contest_id :'266', problem_level :  'B' },
    {serial_no: 4,  problem_name :'Borze', contest_id : '32', problem_level :  'B' },
    {serial_no: 5,  problem_name :'Beautiful Year', contest_id : '271', problem_level :  'A' },
    {serial_no: 6,  problem_name :'Lights Out',  contest_id :'275', problem_level :  'A' },
    {serial_no: 7,  problem_name :'Word', contest_id : '59', problem_level :  'A' },
    {serial_no: 8,  problem_name :'Word Capitalization', contest_id : '281', problem_level :  'A' },
    {serial_no: 9,  problem_name :'Nearly Lucky Number', contest_id : '110', problem_level :  'A' },
    {serial_no: 10, problem_name : 'Stones on the Table', contest_id : '266', problem_level :  'A' },
    {serial_no: 11, problem_name : "Panoramix's Prediction",  contest_id :'80', problem_level :  'A' },
    {serial_no: 12, problem_name : 'Ultra-Fast Mathematician', contest_id : '61', problem_level :  'A' },
    {serial_no: 13, problem_name : 'Perfect Permutation', contest_id : '233', problem_level :  'A' },
    {serial_no: 14, problem_name : 'Arrival of the General',  contest_id :'144', problem_level :  'A' },
    {serial_no: 15, problem_name : 'Drinks',  contest_id :'200', problem_level :  'B' },
    {serial_no: 16, problem_name : 'Insomnia cure', contest_id : '148', problem_level :  'A' },
    {serial_no: 17, problem_name : 'Cupboards',  contest_id :'248', problem_level :  'A' },
    {serial_no: 18, problem_name : 'I_love_username', contest_id : '155', problem_level :  'A' },
    {serial_no: 19, problem_name : 'Tram', contest_id : '116', problem_level :  'A' },
    {serial_no: 20, problem_name : 'Helpful Maths', contest_id : '339', problem_level :  'A' },
    {serial_no: 21, problem_name : 'Is your horseshoe on the other hoof?', contest_id : '228', problem_level :  'A' },
    {serial_no: 22, problem_name : 'Way Too Long Words', contest_id : '71', problem_level :  'A' },
    {serial_no: 23, problem_name : 'Boy or Girl', contest_id : '236', problem_level :  'A' },
    {serial_no: 24, problem_name : 'Amusing Joke', contest_id : '141', problem_level :  'A' },
    {serial_no: 25, problem_name : 'Soft Drinking',  contest_id :'151', problem_level :  'A' },
    {serial_no: 26, problem_name : 'HQ9+', contest_id : '133', problem_level :  'A' },
    {serial_no: 27, problem_name : 'Petya and Strings',  contest_id :'112', problem_level :  'A' },
    {serial_no: 28, problem_name : 'Team',  contest_id :'231', problem_level :  'A' },
    {serial_no: 29, problem_name : 'Bit++', contest_id : '282', problem_level :  'A' },
    {serial_no: 30, problem_name : 'Effective Approach',  contest_id :'227', problem_level :  'B' },
    {serial_no: 31, problem_name : 'Dima and Friends',  contest_id :'272', problem_level :  'A' },
    {serial_no: 32, problem_name : 'Jzzhu and Children', contest_id : '450', problem_level :  'A' },
    {serial_no: 33, problem_name : 'Supercentral Point',  contest_id :'165', problem_level :  'A' },
    {serial_no: 34, problem_name : 'Petr and Book', contest_id : '139', problem_level :  'A' },
    {serial_no: 35, problem_name : 'Parallelepiped',  contest_id :'224', problem_level :  'A' },
    {serial_no: 36, problem_name : 'Reconnaissance 2',  contest_id :'34', problem_level :  'A' },
    {serial_no: 37, problem_name : 'Even Odds', contest_id : '318', problem_level :  'A' },
    {serial_no: 38, problem_name : 'Little Elephant and Rozdil', contest_id : '205', problem_level :  'A' },
    {serial_no: 39, problem_name : "Hexadecimal's theorem", contest_id : '199', problem_level :  'A' },
    {serial_no: 40, problem_name : 'Jeff and Digits', contest_id : '352', problem_level :  'A' },
    {serial_no: 41, problem_name : 'Xenia and Ringroad', contest_id : '339', problem_level :  'B' },
    {serial_no: 42, problem_name : 'Magic Numbers', contest_id : '320', problem_level :  'A' },
    {serial_no: 43, problem_name : 'Translation', contest_id : '41', problem_level :  'A' },
    {serial_no: 44, problem_name : 'Football', contest_id : '43', problem_level :  'A' },
    {serial_no: 45, problem_name : 'Bicycle Chain', contest_id : '215', problem_level :  'A' },
    {serial_no: 46, problem_name : 'Sale',  contest_id :'34', problem_level :  'B' },
    {serial_no: 47, problem_name : 'System of Equations',  contest_id :'214', problem_level :  'A' },
    {serial_no: 48, problem_name : 'Business trip', contest_id : '149', problem_level :  'A' },
    {serial_no: 49, problem_name : 'Dubstep', contest_id : '208', problem_level :  'A' },
    {serial_no: 50, problem_name : 'k-String', contest_id : '219', problem_level :  'A' },
    {serial_no: 51, problem_name : 'The number of positions',  contest_id :'124', problem_level :  'A' },
    {serial_no: 52, problem_name : 'Football',  contest_id :'96', problem_level :  'A' },
    {serial_no: 53, problem_name : 'String Task',  contest_id :'118', problem_level :  'A' },
    {serial_no: 54, problem_name : 'Little Elephant and Function', contest_id : '221', problem_level :  'A' },
    {serial_no: 55, problem_name : 'Present from Lena', contest_id : '118', problem_level :  'B' },
    {serial_no: 56, problem_name : 'Dragons', contest_id : '230', problem_level :  'A' },
    {serial_no: 57, problem_name : 'Puzzles',  contest_id :'337', problem_level :  'A' },
    {serial_no: 58, problem_name : 'Chat room', contest_id : '58', problem_level :  'A' },
    {serial_no: 59, problem_name : 'Airport', contest_id : '218', problem_level :  'B' },
    {serial_no: 60, problem_name : 'DZY Loves Chessboard',  contest_id :'445', problem_level :  'A' },
    {serial_no: 61, problem_name : 'Pashmak and Flowers', contest_id : '459', problem_level :  'B' },
    {serial_no: 62, problem_name : 'Jeff and Periods', contest_id : '352', problem_level :  'B' },
    {serial_no: 63, problem_name : 'Little Girl and Game', contest_id : '276', problem_level :  'B' },
    {serial_no: 64, problem_name : 'Sail', contest_id : '298', problem_level :  'B' },
    {serial_no: 65, problem_name : 'Shower Line',  contest_id :'431', problem_level :  'B' },
    {serial_no: 66, problem_name : 'Shooshuns and Sequence ', contest_id : '222', problem_level :  'A' },
    {serial_no: 67, problem_name : 'Xenia and Divisors', contest_id : '342', problem_level :  'A' },
    {serial_no: 68, problem_name : 'Letter',  contest_id :'43', problem_level :  'B' },
    {serial_no: 69, problem_name : "Kitahara Haruki's Gift", contest_id : '433', problem_level :  'A' },
    {serial_no: 70, problem_name : 'Comparing Strings', contest_id : '186', problem_level :  'A' },
    {serial_no: 71, problem_name : 'Hungry Sequence', contest_id : '327', problem_level :  'B' },
    {serial_no: 72, problem_name : 'Big Segment', contest_id : '242', problem_level :  'B' },
    {serial_no: 73, problem_name : 'Little Elephant and Bits',  contest_id :'258', problem_level :  'A' },
    {serial_no: 74, problem_name : 'Yaroslav and Permutations', contest_id : '296', problem_level :  'A' },
    {serial_no: 75, problem_name : 'Fence',  contest_id :'363', problem_level :  'B' },
    {serial_no: 76, problem_name : 'TL',  contest_id :'350', problem_level :  'A' },
    {serial_no: 77, problem_name : 'Increase and Decrease', contest_id : '246', problem_level :  'B' },
    {serial_no: 78, problem_name : 'Two Bags of Potatoes',  contest_id :'239', problem_level :  'A' },
    {serial_no: 79, problem_name : 'Unlucky Ticket', contest_id : '160', problem_level :  'B' },
    {serial_no: 80, problem_name : 'Boys and Girls',  contest_id :'253', problem_level :  'A' },
    {serial_no: 81, problem_name : 'Easy Number Challenge', contest_id : '236', problem_level :  'B' },
    {serial_no: 82, problem_name : 'Pythagorean Theorem II',  contest_id :'304', problem_level :  'A' },
    {serial_no: 83, problem_name : 'Cards with Numbers', contest_id : '254', problem_level :  'A' },
    {serial_no: 84, problem_name : 'Domino',  contest_id :'353', problem_level :  'A' },
    {serial_no: 85, problem_name : 'Cinema Line',  contest_id :'349', problem_level :  'A' },
    {serial_no: 86, problem_name : 'Rank List',  contest_id :'166', problem_level :  'A' },
    {serial_no: 87, problem_name : 'Cut Ribbon',  contest_id :'189', problem_level :  'A' },
    {serial_no: 88, problem_name : 'IQ Test',  contest_id :'287', problem_level :  'A' },
    {serial_no: 89, problem_name : 'Building Permutation', contest_id : '285', problem_level :  'C' },
    {serial_no: 90, problem_name : "Kuriyama Mirai's Stones", contest_id : '433', problem_level :  'B' },
    {serial_no: 91, problem_name : 'T-primes',  contest_id :'230', problem_level :  'B' },
    {serial_no: 92, problem_name : 'Sereja and Suffixes', contest_id : '368', problem_level :  'B' },
    {serial_no: 93, problem_name : 'Flipping Game',  contest_id :'327', problem_level :  'A' },
    {serial_no: 94, problem_name : 'Free Cash',  contest_id :'237', problem_level :  'A' },
    {serial_no: 95, problem_name : 'Polo the Penguin and Matrix', contest_id : '289', problem_level :  'B' },
    {serial_no: 96, problem_name : 'Jzzhu and Sequences', contest_id : '450', problem_level :  'B' },
    {serial_no: 97, problem_name : 'Appleman and Card Game', contest_id : '462', problem_level :  'B' },
    {serial_no: 98, problem_name : 'Sort the Array',  contest_id :'451', problem_level :  'B' },
    {serial_no: 99, problem_name : 'Sereja and Bottles',  contest_id :'315', problem_level :  'A' },
    {serial_no: 100, problem_name : 'Adding Digits',  contest_id :'260', problem_level :  'A' }
]

module.exports = {ladderproblems}