
  ladderproblems = [
    {serial_no: 1,  problem_name :'Pangram', contest_id : '520', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Fox And Snake',  contest_id :'510', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Insomnia cure', contest_id : '148', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Watching a movie', contest_id : '499', problem_level :  'A' },
    {serial_no: 5,  problem_name :'Dreamoon and WiFi', contest_id : '476', problem_level :  'B' },
    {serial_no: 6,  problem_name :'Playing with Paper',  contest_id :'527', problem_level :  'A' },
    {serial_no: 7,  problem_name :'Link/Cut Tree', contest_id : '614', problem_level :  'A' },
    {serial_no: 8,  problem_name :'Crazy Town',  contest_id :'498', problem_level :  'A' },
    {serial_no: 9,  problem_name :'Mr. Kitayuta, the Treasure Hunter', contest_id : '505', problem_level :  'C' },
    {serial_no: 10, problem_name : 'Tennis Game', contest_id : '496', problem_level :  'D' },
    {serial_no: 11, problem_name : 'Number of Ways',  contest_id :'466', problem_level :  'C' },
    {serial_no: 12, problem_name : 'Error Correct System',  contest_id :'527', problem_level :  'B' },
    {serial_no: 13, problem_name : 'Fight the Monster', contest_id : '487', problem_level :  'A' },
    {serial_no: 14, problem_name : 'Skills', contest_id : '613', problem_level :  'B' },
    {serial_no: 15, problem_name : 'Clique Problem',  contest_id :'527', problem_level :  'D' },
    {serial_no: 16, problem_name : 'Glass Carving',  contest_id :'527', problem_level :  'C' },
    {serial_no: 17, problem_name : 'Edo and Magnets',  contest_id :'594', problem_level :  'C' },
    {serial_no: 18, problem_name : 'Appleman and a Sheet of Paper', contest_id : '461', problem_level :  'C' },
    {serial_no: 19, problem_name : 'Numbers',  contest_id :'128', problem_level :  'D' },
    {serial_no: 20, problem_name : 'Greg and Friends', contest_id : '295', problem_level :  'C' },
    {serial_no: 21, problem_name : 'Watto and Mechanism',  contest_id :'514', problem_level :  'C' },
    {serial_no: 22, problem_name : 'Jeff and Permutation', contest_id : '351', problem_level :  'E' },
    {serial_no: 23, problem_name : 'Sereja and Brackets',  contest_id :'380', problem_level :  'C' },
    {serial_no: 24, problem_name : "Freelancer's Dreams",  contest_id :'605', problem_level :  'C' },
    {serial_no: 25, problem_name : 'Hexagons',  contest_id :'615', problem_level :  'E' },
    {serial_no: 26, problem_name : 'Valid Sets',  contest_id :'486', problem_level :  'D' },
    {serial_no: 27, problem_name : 'Multipliers',  contest_id :'615', problem_level :  'D' },
    {serial_no: 28, problem_name : 'Top Secret Task',  contest_id :'590', problem_level :  'D' },
    {serial_no: 29, problem_name : 'Characteristics of Rectangles',  contest_id :'333', problem_level :  'D' },
    {serial_no: 30, problem_name : 'Tavas and Malekas', contest_id : '535', problem_level :  'D' },
    {serial_no: 31, problem_name : 'Destroying Roads',  contest_id :'543', problem_level :  'B' },
    {serial_no: 32, problem_name : "Mr. Kitayuta's Technology", contest_id : '505', problem_level :  'D' },
    {serial_no: 33, problem_name : 'Maximum Value', contest_id : '484', problem_level :  'B' },
    {serial_no: 34, problem_name : 'Three States',  contest_id :'590', problem_level :  'C' },
    {serial_no: 35, problem_name : 'Antimatter', contest_id : '383', problem_level :  'D' },
    {serial_no: 36, problem_name : 'Dreamoon and Strings', contest_id : '476', problem_level :  'E' },
    {serial_no: 37, problem_name : 'Necklace',  contest_id :'613', problem_level :  'C' },
    {serial_no: 38, problem_name : 'Number Transformation II',  contest_id :'346', problem_level :  'C' },
    {serial_no: 39, problem_name : 'Tricky Function', contest_id : '429', problem_level :  'D' },
    {serial_no: 40, problem_name : 'REQ',  contest_id :'594', problem_level :  'D' },
    {serial_no: 41, problem_name : 'Soldier and Traveling', contest_id : '546', problem_level :  'E' },
    {serial_no: 42, problem_name : 'Board Game',  contest_id :'605', problem_level :  'D' },
    {serial_no: 43, problem_name : 'Jzzhu and Numbers', contest_id : '449', problem_level :  'D' },
    {serial_no: 44, problem_name : 'Name That Tune', contest_id : '498', problem_level :  'B' },
    {serial_no: 45, problem_name : 'Zip-line', contest_id : '650', problem_level :  'D' },
    {serial_no: 46, problem_name : 'Nudist Beach', contest_id : '553', problem_level :  'D' },
    {serial_no: 47, problem_name : "Mr. Kitayuta's Colorful Graph",  contest_id :'506', problem_level :  'D' },
    {serial_no: 48, problem_name : 'Fox And Dinner',  contest_id :'510', problem_level :  'E' },
    {serial_no: 49, problem_name : 'Traffic Jams in the Land', contest_id : '498', problem_level :  'D' },
    {serial_no: 50, problem_name : 'Mike and Frog',  contest_id :'547', problem_level :  'A' },
    {serial_no: 51, problem_name : 'Prefix Product Sequence',  contest_id :'487', problem_level :  'C' },
    {serial_no: 52, problem_name : 'Road Improvement',  contest_id :'543', problem_level :  'D' },
    {serial_no: 53, problem_name : 'Ann and Half-Palindrome', contest_id : '557', problem_level :  'E' },
    {serial_no: 54, problem_name : 'Tanya and Password', contest_id : '508', problem_level :  'D' },
    {serial_no: 55, problem_name : 'Tree and Queries',  contest_id :'375', problem_level :  'D' },
    {serial_no: 56, problem_name : 'Cats Transport', contest_id : '311', problem_level :  'B' },
    {serial_no: 57, problem_name : 'Greg and Caves',  contest_id :'295', problem_level :  'D' },
    {serial_no: 58, problem_name : 'Jzzhu and Apples',  contest_id :'449', problem_level :  'C' },
    {serial_no: 59, problem_name : 'Developing Game', contest_id : '377', problem_level :  'D' },
    {serial_no: 60, problem_name : 'Fuzzy Search', contest_id : '528', problem_level :  'D' },
    {serial_no: 61, problem_name : 'Case of a Top Secret', contest_id : '555', problem_level :  'D' },
    {serial_no: 62, problem_name : 'CNF 2', contest_id : '571', problem_level :  'C' },
    {serial_no: 63, problem_name : 'GukiZ and GukiZiana',  contest_id :'551', problem_level :  'E' },
    {serial_no: 64, problem_name : 'Arthur and Walls', contest_id : '525', problem_level :  'D' },
    {serial_no: 65, problem_name : 'Kingdom and its Cities', contest_id : '613', problem_level :  'D' },
    {serial_no: 66, problem_name : 'Tavas and Pashmaks', contest_id : '535', problem_level :  'E' },
    {serial_no: 67, problem_name : 'Data Center Drama', contest_id : '527', problem_level :  'E' },
    {serial_no: 68, problem_name : 'Hack it!', contest_id : '468', problem_level :  'C' },
    {serial_no: 69, problem_name : 'Remembering Strings', contest_id : '543', problem_level :  'C' },
    {serial_no: 70, problem_name : 'Kindergarten',  contest_id :'484', problem_level :  'D' },
    {serial_no: 71, problem_name : 'DZY Loves Planting',  contest_id :'444', problem_level :  'E' },
    {serial_no: 72, problem_name : 'Tavas in Kansas', contest_id : '536', problem_level :  'D' },
    {serial_no: 73, problem_name : 'Intergalaxy Trips',  contest_id :'605', problem_level :  'E' },
    {serial_no: 74, problem_name : 'Largest Submatrix 3',  contest_id :'407', problem_level :  'D' },
    {serial_no: 75, problem_name : 'Serega and Fun',  contest_id :'455', problem_level :  'D' },
    {serial_no: 76, problem_name : 'Sign on Fence', contest_id : '484', problem_level :  'E' },
    {serial_no: 77, problem_name : 'Ciel and Gondolas',  contest_id :'321', problem_level :  'E' },
    {serial_no: 78, problem_name : 'Sign Posts', contest_id : '568', problem_level :  'D' },
    {serial_no: 79, problem_name : 'Positions in Permutations', contest_id : '285', problem_level :  'E' },
    {serial_no: 80, problem_name : 'Mike and Friends',  contest_id :'547', problem_level :  'E' },
    {serial_no: 81, problem_name : 'Appleman and Complicated Task', contest_id : '461', problem_level :  'D' },
    {serial_no: 82, problem_name : 'Stairs and Lines', contest_id : '498', problem_level :  'E' },
    {serial_no: 83, problem_name : 'Helping People', contest_id : '494', problem_level :  'C' },
    {serial_no: 84, problem_name : 'Birthday',  contest_id :'494', problem_level :  'D' },
    {serial_no: 85, problem_name : 'Dreamoon and Binary', contest_id : '477', problem_level :  'D' },
    {serial_no: 86, problem_name : 'Conveyor Belts',  contest_id :'487', problem_level :  'D' },
    {serial_no: 87, problem_name : 'Mr. Kitayuta vs. Bamboos', contest_id : '505', problem_level :  'E' },
    {serial_no: 88, problem_name : 'A Museum Robbery',  contest_id :'601', problem_level :  'E' },
    {serial_no: 89, problem_name : 'Fox And Travelling', contest_id : '512', problem_level :  'D' },
    {serial_no: 90, problem_name : 'Little Elephant and Broken Sorting',  contest_id :'258', problem_level :  'D' },
    {serial_no: 91, problem_name : 'Mike and Fish',  contest_id :'547', problem_level :  'D' },
    {serial_no: 92, problem_name : 'Strange Sorting',  contest_id :'484', problem_level :  'C' },
    {serial_no: 93, problem_name : 'Case of Computer Network',  contest_id :'555', problem_level :  'E' },
    {serial_no: 94, problem_name : 'Shop', contest_id : '521', problem_level :  'D' },
    {serial_no: 95, problem_name : 'Gerald and Path', contest_id : '559', problem_level :  'E' },
    {serial_no: 96, problem_name : 'Tavas on the Path', contest_id : '536', problem_level :  'E' },
    {serial_no: 97, problem_name : 'Polo the Penguin and Lucky Numbers', contest_id : '288', problem_level :  'E' },
    {serial_no: 98, problem_name : 'Ghd', contest_id : '364', problem_level :  'D' },
    {serial_no: 99, problem_name : 'Warrior and Archer',  contest_id :'594', problem_level :  'A' },
    {serial_no: 100, problem_name : 'Birthday', contest_id : '590', problem_level :  'E' }
  ]
  

  module.exports = {ladderproblems}
  

