
  ladderproblems = [
    {serial_no: 1,  problem_name :'Anton and Letters', contest_id : '443', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Watching a movie',  contest_id :'499', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Expression', contest_id : '479', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Caisa and Pylons', contest_id : '463', problem_level :  'B' },
    {serial_no: 5,  problem_name :'Appleman and Easy Task', contest_id : '462', problem_level :  'A' },
    {serial_no: 6,  problem_name :'DZY Loves Strings', contest_id : '447', problem_level :  'B' },
    {serial_no: 7,  problem_name :'DZY Loves Hash', contest_id : '447', problem_level :  'A' },
    {serial_no: 8,  problem_name :'inc ARG', contest_id : '465', problem_level :  'A' },
    {serial_no: 9,  problem_name :'Inbox (100500)',  contest_id :'465', problem_level :  'B' },
    {serial_no: 10, problem_name : 'Mike and Fax', contest_id : '548', problem_level :  'A' },
    {serial_no: 11, problem_name : 'Caisa and Sugar', contest_id : '463', problem_level :  'A' },
    {serial_no: 12, problem_name : 'Laptops', contest_id : '456', problem_level :  'A' },
    {serial_no: 13, problem_name : 'Set of Strings', contest_id : '544', problem_level :  'A' },
    {serial_no: 14, problem_name : 'DZY Loves Chessboard', contest_id : '445', problem_level :  'A' },
    {serial_no: 15, problem_name : 'Fedya and Maths', contest_id : '456', problem_level :  'B' },
    {serial_no: 16, problem_name : 'Andrey and Problem', contest_id : '442', problem_level :  'B' },
    {serial_no: 17, problem_name : 'Suffix Structures', contest_id : '448', problem_level :  'B' },
    {serial_no: 18, problem_name : 'Towers', contest_id : '479', problem_level :  'B' },
    {serial_no: 19, problem_name : 'Kyoya and Permutation', contest_id : '553', problem_level :  'B' },
    {serial_no: 20, problem_name : 'Kolya and Tandem Repeat', contest_id : '443', problem_level :  'B' },
    {serial_no: 21, problem_name : 'Sea and Islands', contest_id : '544', problem_level :  'B' },
    {serial_no: 22, problem_name : 'Writing Code', contest_id : '543', problem_level :  'A' },
    {serial_no: 23, problem_name : 'Interesting Array', contest_id : '482', problem_level :  'B' },
    {serial_no: 24, problem_name : 'DZY Loves Sequences', contest_id : '446', problem_level :  'A' },
    {serial_no: 25, problem_name : 'DZY Loves Physics', contest_id : '444', problem_level :  'A' },
    {serial_no: 26, problem_name : 'Maximum Xor Secondary',  contest_id :'280', problem_level :  'B' },
    {serial_no: 27, problem_name : 'Two Sets',  contest_id :'468', problem_level :  'B' },
    {serial_no: 28, problem_name : 'Maximum Value',  contest_id :'484', problem_level :  'B' },
    {serial_no: 29, problem_name : 'Jeff and Permutation', contest_id : '351', problem_level :  'E' },
    {serial_no: 30, problem_name : 'Case of Fugitive', contest_id :'555', problem_level :  'B' },
    {serial_no: 31, problem_name : 'Main Sequence',  contest_id :'286', problem_level :  'C' },
    {serial_no: 32, problem_name : 'Gargari and Permutations', contest_id : '463', problem_level :  'D' },
    {serial_no: 33, problem_name : 'Vanya and Scales', contest_id : '552', problem_level :  'C' },
    {serial_no: 34, problem_name : 'Appleman and Tree', contest_id : '461', problem_level :  'B' },
    {serial_no: 35, problem_name : 'Soldier and Number Game',  contest_id :'546', problem_level :  'D' },
    {serial_no: 36, problem_name : 'Propagating tree', contest_id : '383', problem_level :  'C' },
    {serial_no: 37, problem_name : 'Array and Operations', contest_id : '498', problem_level :  'C' },
    {serial_no: 38, problem_name : 'Restore Cube ', contest_id : '464', problem_level :  'B' },
    {serial_no: 39, problem_name : 'Dima and Trap Graph',  contest_id :'366', problem_level :  'D' },
    {serial_no: 40, problem_name : 'Civilization',  contest_id :'455', problem_level :  'C' },
    {serial_no: 41, problem_name : 'Destroying Roads',  contest_id :'543', problem_level :  'B' },
    {serial_no: 42, problem_name : 'Painting Fence', contest_id : '448', problem_level :  'C' },
    {serial_no: 43, problem_name : 'Little Pony and Summer Sun Celebration', contest_id : '453', problem_level :  'C' },
    {serial_no: 44, problem_name : 'Shifting', contest_id : '286', problem_level :  'B' },
    {serial_no: 45, problem_name : 'Gargari and Bishops',  contest_id :'463', problem_level :  'C' },
    {serial_no: 46, problem_name : 'Appleman and a Sheet of Paper', contest_id : '461', problem_level :  'C' },
    {serial_no: 47, problem_name : 'Jzzhu and Chocolate', contest_id : '449', problem_level :  'A' },
    {serial_no: 48, problem_name : 'Drazil and Tiles',  contest_id :'515', problem_level :  'D' },
    {serial_no: 49, problem_name : 'Kalila and Dimna in the Logging Industry', contest_id : '319', problem_level :  'C' },
    {serial_no: 50, problem_name : 'Equivalent Strings',  contest_id :'559', problem_level :  'B' },
    {serial_no: 51, problem_name : 'Substitutes in Number', contest_id : '464', problem_level :  'C' },
    {serial_no: 52, problem_name : 'Jzzhu and Cities',  contest_id :'449', problem_level :  'B' },
    {serial_no: 53, problem_name : 'Information Graph', contest_id : '466', problem_level :  'E' },
    {serial_no: 54, problem_name : 'Mike and Foam',  contest_id :'547', problem_level :  'C' },
    {serial_no: 55, problem_name : 'Brackets in Implications', contest_id : '550', problem_level :  'E' },
    {serial_no: 56, problem_name : 'Hill Climbing', contest_id : '406', problem_level :  'D' },
    {serial_no: 57, problem_name : 'Divisors',  contest_id :'448', problem_level :  'E' },
    {serial_no: 58, problem_name : 'Tree Requests', contest_id : '570', problem_level :  'D' },
    {serial_no: 59, problem_name : 'DZY Loves FFT', contest_id : '444', problem_level :  'B' },
    {serial_no: 60, problem_name : 'Guess the Tree',  contest_id :'429', problem_level :  'C' },
    {serial_no: 61, problem_name : 'Caisa and Tree',  contest_id :'463', problem_level :  'E' },
    {serial_no: 62, problem_name : 'Darth Vader and Tree',  contest_id :'514', problem_level :  'E' },
    {serial_no: 63, problem_name : 'Prefix Product Sequence', contest_id : '487', problem_level :  'C' },
    {serial_no: 64, problem_name : 'Traffic Jams in the Land', contest_id : '498', problem_level :  'D' },
    {serial_no: 65, problem_name : 'Name That Tune', contest_id : '498', problem_level :  'B' },
    {serial_no: 66, problem_name : "Mr. Kitayuta's Colorful Graph",  contest_id :'506', problem_level :  'D' },
    {serial_no: 67, problem_name : 'Tricky Function', contest_id : '429', problem_level :  'D' },
    {serial_no: 68, problem_name : 'Drazil and Park', contest_id : '515', problem_level :  'E' },
    {serial_no: 69, problem_name : 'The Child and Sequence', contest_id : '438', problem_level :  'D' },
    {serial_no: 70, problem_name : 'Road Improvement', contest_id : '543', problem_level :  'D' },
    {serial_no: 71, problem_name : 'Dreamoon and Strings',  contest_id :'476', problem_level :  'E' },
    {serial_no: 72, problem_name : 'Fox And Dinner', contest_id : '510', problem_level :  'E' },
    {serial_no: 73, problem_name : 'Jzzhu and Numbers',  contest_id :'449', problem_level :  'D' },
    {serial_no: 74, problem_name : 'Adam and Tree',  contest_id :'442', problem_level :  'D' },
    {serial_no: 75, problem_name : 'Remembering Strings', contest_id : '543', problem_level :  'C' },
    {serial_no: 76, problem_name : 'Alex and Complicated Task', contest_id : '467', problem_level :  'E' },
    {serial_no: 77, problem_name : 'Tree and Queries', contest_id : '375', problem_level :  'D' },
    {serial_no: 78, problem_name : "Tachibana Kanade's Tofu",  contest_id :'433', problem_level :  'E' },
    {serial_no: 79, problem_name : 'DZY Loves Strings', contest_id : '444', problem_level :  'D' },
    {serial_no: 80, problem_name : 'Guess Your Way Out! II', contest_id : '558', problem_level :  'D' },
    {serial_no: 81, problem_name : 'XOR and Favorite Number',  contest_id :'617', problem_level :  'E' },
    {serial_no: 82, problem_name : 'Volcanoes',  contest_id :'383', problem_level :  'B' },
    {serial_no: 83, problem_name : 'Artem and Array ', contest_id : '442', problem_level :  'C' },
    {serial_no: 84, problem_name : 'Arthur and Walls',  contest_id :'525', problem_level :  'D' },
    {serial_no: 85, problem_name : 'Fedor and Essay', contest_id : '467', problem_level :  'D' },
    {serial_no: 86, problem_name : 'Pig and Palindromes', contest_id : '570', problem_level :  'E' },
    {serial_no: 87, problem_name : 'GukiZ and Binary Operations', contest_id :'551', problem_level :  'D' },
    {serial_no: 88, problem_name : 'Hack it!',  contest_id :'468', problem_level :  'C' },
    {serial_no: 89, problem_name : 'Case of a Top Secret', contest_id : '555', problem_level :  'D' },
    {serial_no: 90, problem_name : 'GukiZ and GukiZiana',  contest_id :'551', problem_level :  'E' },
    {serial_no: 91, problem_name : 'DZY Loves Fibonacci Numbers',  contest_id :'446', problem_level :  'C' },
    {serial_no: 92, problem_name : 'Jzzhu and Apples',  contest_id :'449', problem_level :  'C' },
    {serial_no: 93, problem_name : 'Vowels',  contest_id :'383', problem_level :  'E' },
    {serial_no: 94, problem_name : 'Ciel and Gondolas',  contest_id :'321', problem_level :  'E' },
    {serial_no: 95, problem_name : 'Game with Strings',  contest_id :'482', problem_level :  'C' },
    {serial_no: 96, problem_name : 'Helping People', contest_id : '494', problem_level :  'C' },
    {serial_no: 97, problem_name : 'Mike and Fish', contest_id : '547', problem_level :  'D' },
    {serial_no: 98, problem_name : 'Mike and Friends', contest_id : '547', problem_level :  'E' },
    {serial_no: 99, problem_name : 'Serega and Fun',  contest_id :'455', problem_level :  'D' },
    {serial_no: 100, problem_name : 'Function', contest_id : '455', problem_level :  'E' }
  ]

  module.exports = {ladderproblems}