
  ladderproblems = [
    {serial_no: 1,  problem_name :'Sereja and Dima', contest_id : '381', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Gravity Flip',  contest_id :'405', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Little Pony and Crystal Mine',  contest_id :'454', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Anton and Letters',  contest_id :'443', problem_level :  'A' },
    {serial_no: 5,  problem_name :'Fox And Snake', contest_id : '510', problem_level :  'A' },
    {serial_no: 6,  problem_name :'inc ARG',  contest_id :'465', problem_level :  'A' },
    {serial_no: 7,  problem_name :'Caisa and Pylons', contest_id : '463', problem_level :  'B' },
    {serial_no: 8,  problem_name :'Puzzles',  contest_id :'337', problem_level :  'A' },
    {serial_no: 9,  problem_name :'Chat room',  contest_id :'58', problem_level :  'A' },
    {serial_no: 10, problem_name : 'Vasya and Socks',  contest_id :'460', problem_level :  'A' },
    {serial_no: 11, problem_name : 'I Wanna Be the Guy',  contest_id :'469', problem_level :  'A' },
    {serial_no: 12, problem_name : 'Expression', contest_id : '479', problem_level :  'A' },
    {serial_no: 13, problem_name : 'Counterexample ', contest_id : '483', problem_level :  'A' },
    {serial_no: 14, problem_name : 'Flipping Game',  contest_id :'327', problem_level :  'A' },
    {serial_no: 15, problem_name : 'Pashmak and Garden',  contest_id :'459', problem_level :  'A' },
    {serial_no: 16, problem_name : 'Ilya and Queries',  contest_id :'313', problem_level :  'B' },
    {serial_no: 17, problem_name : 'Cheap Travel',  contest_id :'466', problem_level :  'A' },
    {serial_no: 18, problem_name : 'Little Pony and Expected Maximum', contest_id : '453', problem_level :  'A' },
    {serial_no: 19, problem_name : 'Caisa and Sugar',  contest_id :'463', problem_level :  'A' },
    {serial_no: 20, problem_name : 'Cut Ribbon', contest_id : '189', problem_level :  'A' },
    {serial_no: 21, problem_name : 'Writing Code',  contest_id :'543', problem_level :  'A' },
    {serial_no: 22, problem_name : 'Tennis Game',  contest_id :'496', problem_level :  'D' },
    {serial_no: 23, problem_name : 'Towers',  contest_id :'479', problem_level :  'B' },
    {serial_no: 24, problem_name : "Ryouko's Memory Note",  contest_id :'433', problem_level :  'C' },
    {serial_no: 25, problem_name : 'Knight Tournament',  contest_id :'356', problem_level :  'A' },
    {serial_no: 26, problem_name : 'Andrey and Problem',  contest_id :'442', problem_level :  'B' },
    {serial_no: 27, problem_name : 'Password',  contest_id :'126', problem_level :  'B' },
    {serial_no: 28, problem_name : 'Interesting Array', contest_id : '482', problem_level :  'B' },
    {serial_no: 29, problem_name : 'Fox And Two Dots', contest_id : '510', problem_level :  'B' },
    {serial_no: 30, problem_name : 'Xenia and Bit Operations',  contest_id :'339', problem_level :  'D' },
    {serial_no: 31, problem_name : 'k-Tree',  contest_id :'431', problem_level :  'C' },
    {serial_no: 32, problem_name : 'Read Time',  contest_id :'343', problem_level :  'C' },
    {serial_no: 33, problem_name : 'Boredom', contest_id : '455', problem_level :  'A' },
    {serial_no: 34, problem_name : 'Fools and Roads',  contest_id :'191', problem_level :  'C' },
    {serial_no: 35, problem_name : 'DZY Loves Sequences',  contest_id :'446', problem_level :  'A' },
    {serial_no: 36, problem_name : 'Breaking Good', contest_id : '507', problem_level :  'E' },
    {serial_no: 37, problem_name : 'Red-Green Towers', contest_id : '478', problem_level :  'D' },
    {serial_no: 38, problem_name : 'Pashmak and Buses', contest_id : '459', problem_level :  'C' },
    {serial_no: 39, problem_name : 'Mashmokh and Reverse Operation',  contest_id :'414', problem_level :  'C' },
    {serial_no: 40, problem_name : 'Sereja and Table ', contest_id : '425', problem_level :  'B' },
    {serial_no: 41, problem_name : 'R2D2 and Droid Army',  contest_id :'514', problem_level :  'D' },
    {serial_no: 42, problem_name : 'Strip', contest_id : '487', problem_level :  'B' },
    {serial_no: 43, problem_name : 'Destroying Roads',  contest_id :'543', problem_level :  'B' },
    {serial_no: 44, problem_name : 'A and B and Lecture Rooms', contest_id : '519', problem_level :  'E' },
    {serial_no: 45, problem_name : 'Obsessive String', contest_id : '494', problem_level :  'B' },
    {serial_no: 46, problem_name : 'Restore Cube ', contest_id : '464', problem_level :  'B' },
    {serial_no: 47, problem_name : 'Roman and Numbers',  contest_id :'401', problem_level :  'D' },
    {serial_no: 48, problem_name : 'Water Tree',  contest_id :'343', problem_level :  'D' },
    {serial_no: 49, problem_name : 'Towers', contest_id : '229', problem_level :  'D' },
    {serial_no: 50, problem_name : 'Maximum Value',  contest_id :'484', problem_level :  'B' },
    {serial_no: 51, problem_name : 'Valera and Swaps',  contest_id :'441', problem_level :  'D' },
    {serial_no: 52, problem_name : 'Increase Sequence', contest_id : '466', problem_level :  'D' },
    {serial_no: 53, problem_name : 'Wonder Room', contest_id : '466', problem_level :  'B' },
    {serial_no: 54, problem_name : 'Devu and Partitioning of the Array',  contest_id :'439', problem_level :  'C' },
    {serial_no: 55, problem_name : 'Gerald and Giant Chess',  contest_id :'559', problem_level :  'C' },
    {serial_no: 56, problem_name : 'Watching Fireworks is Fun', contest_id : '372', problem_level :  'C' },
    {serial_no: 57, problem_name : 'Jeff and Rounding',  contest_id :'351', problem_level :  'A' },
    {serial_no: 58, problem_name : 'Ciel the Commander',  contest_id :'321', problem_level :  'C' },
    {serial_no: 59, problem_name : 'Painting Fence', contest_id : '448', problem_level :  'C' },
    {serial_no: 60, problem_name : 'Little Pony and Harmony Chest',  contest_id :'453', problem_level :  'B' },
    {serial_no: 61, problem_name : 'Case of Chocolate',  contest_id :'555', problem_level :  'C' },
    {serial_no: 62, problem_name : 'Lucky Common Subsequence', contest_id : '346', problem_level :  'B' },
    {serial_no: 63, problem_name : 'Sereja and Brackets',  contest_id :'380', problem_level :  'C' },
    {serial_no: 64, problem_name : 'Kalila and Dimna in the Logging Industry', contest_id : '319', problem_level :  'C' },
    {serial_no: 65, problem_name : 'String',  contest_id :'128', problem_level :  'B' },
    {serial_no: 66, problem_name : 'Civilization',  contest_id :'455', problem_level :  'C' },
    {serial_no: 67, problem_name : 'XOR on Segment', contest_id : '242', problem_level :  'E' },
    {serial_no: 68, problem_name : 'Prefixes and Suffixes',  contest_id :'432', problem_level :  'D' },
    {serial_no: 69, problem_name : 'Appleman and Tree', contest_id : '461', problem_level :  'B' },
    {serial_no: 70, problem_name : 'Enemy is weak',  contest_id :'61', problem_level :  'E' },
    {serial_no: 71, problem_name : 'Jzzhu and Cities', contest_id : '449', problem_level :  'B' },
    {serial_no: 72, problem_name : 'Substitutes in Number',  contest_id :'464', problem_level :  'C' },
    {serial_no: 73, problem_name : 'Little Elephant and Array', contest_id : '220', problem_level :  'B' },
    {serial_no: 74, problem_name : 'Pashmak and Graph',  contest_id :'459', problem_level :  'E' },
    {serial_no: 75, problem_name : 'Propagating tree', contest_id : '383', problem_level :  'C' },
    {serial_no: 76, problem_name : 'Match & Catch',  contest_id :'427', problem_level :  'D' },
    {serial_no: 77, problem_name : 'A Simple Task',  contest_id :'558', problem_level :  'E' },
    {serial_no: 78, problem_name : 'Prefix Product Sequence', contest_id : '487', problem_level :  'C' },
    {serial_no: 79, problem_name : 'Vasya and Beautiful Arrays', contest_id : '354', problem_level :  'C' },
    {serial_no: 80, problem_name : 'Road Improvement', contest_id : '543', problem_level :  'D' },
    {serial_no: 81, problem_name : 'Tree Requests', contest_id : '570', problem_level :  'D' },
    {serial_no: 82, problem_name : 'Sereja and Squares', contest_id : '425', problem_level :  'D' },
    {serial_no: 83, problem_name : 'LIS of Sequence', contest_id : '486', problem_level :  'E' },
    {serial_no: 84, problem_name : 'Jzzhu and Numbers',  contest_id :'449', problem_level :  'D' },
    {serial_no: 85, problem_name : 'Captains Mode', contest_id : '377', problem_level :  'C' },
    {serial_no: 86, problem_name : 'Mike and Foam', contest_id : '547', problem_level :  'C' },
    {serial_no: 87, problem_name : 'Devu and Birthday Celebration', contest_id : '439', problem_level :  'E' },
    {serial_no: 88, problem_name : 'Martian Strings',  contest_id :'149', problem_level :  'E' },
    {serial_no: 89, problem_name : 'Hill Climbing', contest_id : '406', problem_level :  'D' },
    {serial_no: 90, problem_name : 'Antimatter', contest_id : '383', problem_level :  'D' },
    {serial_no: 91, problem_name : 'Tricky Function', contest_id : '429', problem_level :  'D' },
    {serial_no: 92, problem_name : 'The Child and Sequence',  contest_id :'438', problem_level :  'D' },
    {serial_no: 93, problem_name : 'Tanya and Password', contest_id : '508', problem_level :  'D' },
    {serial_no: 94, problem_name : 'Fedor and Essay', contest_id : '467', problem_level :  'D' },
    {serial_no: 95, problem_name : 'Xenia and Tree',  contest_id :'342', problem_level :  'E' },
    {serial_no: 96, problem_name : 'DZY Loves Fibonacci Numbers',  contest_id :'446', problem_level :  'C' },
    {serial_no: 97, problem_name : 'Ann and Half-Palindrome', contest_id : '557', problem_level :  'E' },
    {serial_no: 98, problem_name : 'Kindergarten', contest_id : '484', problem_level :  'D' },
    {serial_no: 99, problem_name : 'Tree and Queries',  contest_id :'375', problem_level :  'D' },
    {serial_no: 100, problem_name : 'Serega and Fun',  contest_id :'455', problem_level :  'D' }
  ]

  module.exports = {ladderproblems};