ladderproblems = [
    {serial_no: 1,  problem_name :'Presents', contest_id : '136', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Nearly Lucky Number', contest_id : '110', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Petya and Strings',  contest_id :'112', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Tram', contest_id : '116', problem_level :  'A' },
    {serial_no: 5,  problem_name :'Ultra-Fast Mathematician', contest_id : '61', problem_level :  'A' },
    {serial_no: 6,  problem_name :'Amusing Joke',  contest_id :'141', problem_level :  'A' },
    {serial_no: 7,  problem_name :'Way Too Long Words',  contest_id :'71', problem_level :  'A' },
    {serial_no: 8,  problem_name :'Xenia and Ringroad', contest_id : '339', problem_level :  'B' },
    {serial_no: 9,  problem_name :'Slightly Decreasing Permutations', contest_id : '285', problem_level :  'A' },
    {serial_no: 10, problem_name : 'Football', contest_id : '96', problem_level :  'A' },
    {serial_no: 11, problem_name : 'Caisa and Pylons', contest_id : '463', problem_level :  'B' },
    {serial_no: 12, problem_name : 'Present from Lena',  contest_id :'118', problem_level :  'B' },
    {serial_no: 13, problem_name : 'k-String',  contest_id :'219', problem_level :  'A' },
    {serial_no: 14, problem_name : 'Fancy Fence', contest_id : '270', problem_level :  'A' },
    {serial_no: 15, problem_name : 'Chat room', contest_id : '58', problem_level :  'A' },
    {serial_no: 16, problem_name : 'Contest', contest_id : '501', problem_level :  'A' },
    {serial_no: 17, problem_name : 'Twins', contest_id : '160', problem_level :  'A' },
    {serial_no: 18, problem_name : 'Puzzles', contest_id : '337', problem_level :  'A' },
    {serial_no: 19, problem_name : 'String Task',  contest_id :'118', problem_level :  'A' },
    {serial_no: 20, problem_name : 'Mashmokh and ACM',  contest_id :'414', problem_level :  'B' },
    {serial_no: 21, problem_name : 'The Child and Toy', contest_id : '437', problem_level :  'C' },
    {serial_no: 22, problem_name : 'Fence', contest_id : '363', problem_level :  'B' },
    {serial_no: 23, problem_name : 'T-primes',  contest_id :'230', problem_level :  'B' },
    {serial_no: 24, problem_name : 'Rank List',  contest_id :'166', problem_level :  'A' },
    {serial_no: 25, problem_name : 'Fox and Box Accumulation', contest_id : '388', problem_level :  'A' },
    {serial_no: 26, problem_name : 'Cinema Line',  contest_id :'349', problem_level :  'A' },
    {serial_no: 27, problem_name : 'Escape from Stones',  contest_id :'264', problem_level :  'A' },
    {serial_no: 28, problem_name : 'Laptops', contest_id : '456', problem_level :  'A' },
    {serial_no: 29, problem_name : 'Little Elephant and Bits',  contest_id :'258', problem_level :  'A' },
    {serial_no: 30, problem_name : 'Flipping Game', contest_id : '327', problem_level :  'A' },
    {serial_no: 31, problem_name : 'Mashmokh and ACM',  contest_id :'414', problem_level :  'B' },
    {serial_no: 32, problem_name : 'Dima and Staircase',  contest_id :'272', problem_level :  'C' },
    {serial_no: 33, problem_name : 'Building Permutation',  contest_id :'285', problem_level :  'C' },
    {serial_no: 34, problem_name : 'Ilya and Queries', contest_id : '313', problem_level :  'B' },
    {serial_no: 35, problem_name : "Kuriyama Mirai's Stones",  contest_id :'433', problem_level :  'B' },
    {serial_no: 36, problem_name : 'Party',  contest_id :'115', problem_level :  'A' },
    {serial_no: 37, problem_name : 'Ice Skating', contest_id : '217', problem_level :  'A' },
    {serial_no: 38, problem_name : 'Cut Ribbon', contest_id : '189', problem_level :  'A' },
    {serial_no: 39, problem_name : 'Booking System',  contest_id :'416', problem_level :  'C' },
    {serial_no: 40, problem_name : 'Fox And Names',  contest_id :'510', problem_level :  'C' },
    {serial_no: 41, problem_name : 'Fox And Two Dots',  contest_id :'510', problem_level :  'B' },
    {serial_no: 42, problem_name : 'Pocket Book',  contest_id :'152', problem_level :  'C' },
    {serial_no: 43, problem_name : 'Array',  contest_id :'224', problem_level :  'B' },
    {serial_no: 44, problem_name : 'Ladder',  contest_id :'279', problem_level :  'C' },
    {serial_no: 45, problem_name : 'Divisibility by Eight', contest_id : '550', problem_level :  'C' },
    {serial_no: 46, problem_name : 'Little Elephant and Problem', contest_id : '220', problem_level :  'A' },
    {serial_no: 47, problem_name : 'Ciel and Flowers', contest_id : '322', problem_level :  'B' },
    {serial_no: 48, problem_name : 'Convex Shape',  contest_id :'275', problem_level :  'B' },
    {serial_no: 49, problem_name : 'Maze',  contest_id :'377', problem_level :  'A' },
    {serial_no: 50, problem_name : 'View Angle',  contest_id :'257', problem_level :  'C' },
    {serial_no: 51, problem_name : 'Mr. Kitayuta, the Treasure Hunter',  contest_id :'505', problem_level :  'C' },
    {serial_no: 52, problem_name : 'Maximum Absurdity',  contest_id :'332', problem_level :  'B' },
    {serial_no: 53, problem_name : 'Color Stripe',  contest_id :'219', problem_level :  'C' },
    {serial_no: 54, problem_name : 'Checkposts',  contest_id :'427', problem_level :  'C' },
    {serial_no: 55, problem_name : 'Misha and Forest', contest_id : '501', problem_level :  'C' },
    {serial_no: 56, problem_name : 'Kolya and Tandem Repeat',  contest_id :'443', problem_level :  'B' },
    {serial_no: 57, problem_name : 'Anya and Ghosts', contest_id : '508', problem_level :  'C' },
    {serial_no: 58, problem_name : 'Removing Columns', contest_id : '496', problem_level :  'C' },
    {serial_no: 59, problem_name : 'Beautiful Numbers', contest_id : '300', problem_level :  'C' },
    {serial_no: 60, problem_name : 'Vasya and Chess',  contest_id :'493', problem_level :  'D' },
    {serial_no: 61, problem_name : 'Hamburgers', contest_id : '371', problem_level :  'C' },
    {serial_no: 62, problem_name : 'Colorful Graph',  contest_id :'246', problem_level :  'D' },
    {serial_no: 63, problem_name : 'To Add or Not to Add', contest_id : '231', problem_level :  'C' },
    {serial_no: 64, problem_name : 'Xenia and Bit Operations', contest_id : '339', problem_level :  'D' },
    {serial_no: 65, problem_name : 'Little Girl and Maximum XOR',  contest_id :'276', problem_level :  'D' },
    {serial_no: 66, problem_name : 'Arithmetic Progression', contest_id : '382', problem_level :  'C' },
    {serial_no: 67, problem_name : 'Friends and Presents', contest_id : '483', problem_level :  'B' },
    {serial_no: 68, problem_name : 'Barcode',  contest_id :'225', problem_level :  'C' },
    {serial_no: 69, problem_name : 'Xenia and Weights',  contest_id :'339', problem_level :  'C' },
    {serial_no: 70, problem_name : 'Little Dima and Equation', contest_id : '460', problem_level :  'B' },
    {serial_no: 71, problem_name : 'Long Jumps', contest_id : '479', problem_level :  'D' },
    {serial_no: 72, problem_name : 'Tetrahedron',  contest_id :'166', problem_level :  'E' },
    {serial_no: 73, problem_name : 'Physics Practical', contest_id : '253', problem_level :  'B' },
    {serial_no: 74, problem_name : 'Boredom',  contest_id :'455', problem_level :  'A' },
    {serial_no: 75, problem_name : 'Valera and Tubes ',  contest_id :'441', problem_level :  'C' },
    {serial_no: 76, problem_name : 'Valera and Elections',  contest_id :'369', problem_level :  'C' },
    {serial_no: 77, problem_name : 'Little Girl and Maximum Sum',  contest_id :'276', problem_level :  'C' },
    {serial_no: 78, problem_name : 'George and Job', contest_id : '467', problem_level :  'C' },
    {serial_no: 79, problem_name : 'Table Decorations',  contest_id :'478', problem_level :  'C' },
    {serial_no: 80, problem_name : 'k-Tree',  contest_id :'431', problem_level :  'C' },
    {serial_no: 81, problem_name : 'Color the Fence', contest_id : '349', problem_level :  'B' },
    {serial_no: 82, problem_name : 'Polo the Penguin and Matrix', contest_id : '289', problem_level :  'B' },
    {serial_no: 83, problem_name : 'Another Problem on Strings',  contest_id :'165', problem_level :  'C' },
    {serial_no: 84, problem_name : 'Exams',  contest_id :'479', problem_level :  'C' },
    {serial_no: 85, problem_name : "Caesar's Legions", contest_id : '118', problem_level :  'D' },
    {serial_no: 86, problem_name : 'Beautiful Sets of Points', contest_id : '268', problem_level :  'C' },
    {serial_no: 87, problem_name : 'Boredom',  contest_id :'455', problem_level :  'A' },
    {serial_no: 88, problem_name : 'Number of Ways',  contest_id :'466', problem_level :  'C' },
    {serial_no: 89, problem_name : 'A and B and Interesting Substrings', contest_id : '519', problem_level :  'D' },
    {serial_no: 90, problem_name : 'Valid Sets',  contest_id :'486', problem_level :  'D' },
    {serial_no: 91, problem_name : 'Devu and Partitioning of the Array', contest_id : '439', problem_level :  'C' },
    {serial_no: 92, problem_name : 'Good Substrings',  contest_id :'271', problem_level :  'D' },
    {serial_no: 93, problem_name : 'Wonder Room',  contest_id :'466', problem_level :  'B' },
    {serial_no: 94, problem_name : 'Present', contest_id : '460', problem_level :  'C' },
    {serial_no: 95, problem_name : 'Painting Fence',  contest_id :'448', problem_level :  'C' },
    {serial_no: 96, problem_name : 'Vasya and Basketball', contest_id : '493', problem_level :  'C' },
    {serial_no: 97, problem_name : 'Bear and Prime Numbers', contest_id : '385', problem_level :  'C' },
    {serial_no: 98, problem_name : 'Restore Graph', contest_id : '404', problem_level :  'C' },
    {serial_no: 99, problem_name : 'Gargari and Bishops', contest_id : '463', problem_level :  'C' },
    {serial_no: 100, problem_name : 'Multiplication Table', contest_id : '448', problem_level :  'D' }
]

module.exports = {ladderproblems}
