
  ladderproblems = [
    {serial_no: 1,  problem_name :'Boy or Girl', contest_id : '236', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Beautiful Matrix',  contest_id :'263', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Team', contest_id : '231', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Petya and Strings', contest_id : '112', problem_level :  'A' },
    {serial_no: 5,  problem_name :'Magnets',  contest_id :'344', problem_level :  'A' },
    {serial_no: 6,  problem_name :'Young Physicist', contest_id : '69', problem_level :  'A' },
    {serial_no: 7,  problem_name :'Word Capitalization', contest_id : '281', problem_level :  'A' },
    {serial_no: 8,  problem_name :'Bit++', contest_id : '282', problem_level :  'A' },
    {serial_no: 9,  problem_name :'Way Too Long Words', contest_id : '71', problem_level :  'A' },
    {serial_no: 10, problem_name : 'Even Odds', contest_id : '318', problem_level :  'A' },
    {serial_no: 11, problem_name : 'Dubstep', contest_id : '208', problem_level :  'A' },
    {serial_no: 12, problem_name : 'Xenia and Ringroad',  contest_id :'339', problem_level :  'B' },
    {serial_no: 13, problem_name : 'Football', contest_id : '96', problem_level :  'A' },
    {serial_no: 14, problem_name : 'System of Equations',  contest_id :'214', problem_level :  'A' },
    {serial_no: 15, problem_name : 'Lucky Division', contest_id : '122', problem_level :  'A' },
    {serial_no: 16, problem_name : 'Dragons', contest_id : '230', problem_level :  'A' },
    {serial_no: 17, problem_name : 'Puzzles', contest_id : '337', problem_level :  'A' },
    {serial_no: 18, problem_name : 'Chat room', contest_id : '58', problem_level :  'A' },
    {serial_no: 19, problem_name : 'Dreamoon and WiFi', contest_id : '476', problem_level :  'B' },
    {serial_no: 20, problem_name : 'Ice Skating', contest_id : '217', problem_level :  'A' },
    {serial_no: 21, problem_name : 'Learning Languages', contest_id : '277', problem_level :  'A' },
    {serial_no: 22, problem_name : 'T-primes',  contest_id :'230', problem_level :  'B' },
    {serial_no: 23, problem_name : 'Fence',  contest_id :'363', problem_level :  'B' },
    {serial_no: 24, problem_name : 'Party', contest_id : '115', problem_level :  'A' },
    {serial_no: 25, problem_name : 'Building Permutation', contest_id : '285', problem_level :  'C' },
    {serial_no: 26, problem_name : 'Greg and Array', contest_id : '295', problem_level :  'A' },
    {serial_no: 27, problem_name : 'Cut Ribbon', contest_id : '189', problem_level :  'A' },
    {serial_no: 28, problem_name : 'Maximum Absurdity',  contest_id :'332', problem_level :  'B' },
    {serial_no: 29, problem_name : 'Vasya and Chess', contest_id : '493', problem_level :  'D' },
    {serial_no: 30, problem_name : 'Bubble Sort Graph', contest_id : '340', problem_level :  'D' },
    {serial_no: 31, problem_name : 'Modified GCD', contest_id : '75', problem_level :  'C' },
    {serial_no: 32, problem_name : 'Palindrome Transformation',  contest_id :'486', problem_level :  'C' },
    {serial_no: 33, problem_name : 'Mafia',  contest_id :'348', problem_level :  'A' },
    {serial_no: 34, problem_name : 'To Add or Not to Add',  contest_id :'231', problem_level :  'C' },
    {serial_no: 35, problem_name : 'Almost Arithmetical Progression',  contest_id :'255', problem_level :  'C' },
    {serial_no: 36, problem_name : 'DZY Loves Sequences',  contest_id :'446', problem_level :  'A' },
    {serial_no: 37, problem_name : 'Ilya and Matrix',  contest_id :'313', problem_level :  'C' },
    {serial_no: 38, problem_name : 'Physics Practical', contest_id : '253', problem_level :  'B' },
    {serial_no: 39, problem_name : 'Common Divisors', contest_id : '182', problem_level :  'D' },
    {serial_no: 40, problem_name : 'Valera and Elections',  contest_id :'369', problem_level :  'C' },
    {serial_no: 41, problem_name : 'XOR and OR', contest_id : '282', problem_level :  'C' },
    {serial_no: 42, problem_name : 'Color the Fence', contest_id : '349', problem_level :  'B' },
    {serial_no: 43, problem_name : 'Colorful Graph',  contest_id :'246', problem_level :  'D' },
    {serial_no: 44, problem_name : 'Boredom',  contest_id :'455', problem_level :  'A' },
    {serial_no: 45, problem_name : 'Hometask', contest_id : '214', problem_level :  'B' },
    {serial_no: 46, problem_name : 'k-Tree', contest_id : '431', problem_level :  'C' },
    {serial_no: 47, problem_name : 'Bombs', contest_id : '350', problem_level :  'C' },
    {serial_no: 48, problem_name : 'Beautiful Numbers', contest_id : '300', problem_level :  'C' },
    {serial_no: 49, problem_name : 'Shaass and Bookshelf', contest_id : '294', problem_level :  'B' },
    {serial_no: 50, problem_name : 'Password', contest_id : '126', problem_level :  'B' },
    {serial_no: 51, problem_name : 'Fixing Typos', contest_id : '363', problem_level :  'C' },
    {serial_no: 52, problem_name : 'Zero Tree',  contest_id :'274', problem_level :  'B' },
    {serial_no: 53, problem_name : 'Pipeline',  contest_id :'287', problem_level :  'B' },
    {serial_no: 54, problem_name : 'Greenhouse Effect', contest_id :'269', problem_level :  'B' },
    {serial_no: 55, problem_name : 'Hamburgers',  contest_id :'371', problem_level :  'C' },
    {serial_no: 56, problem_name : 'Little Girl and Maximum XOR', contest_id : '276', problem_level :  'D' },
    {serial_no: 57, problem_name : 'Dima and Hares',  contest_id :'358', problem_level :  'D' },
    {serial_no: 58, problem_name : 'Another Problem on Strings', contest_id : '165', problem_level :  'C' },
    {serial_no: 59, problem_name : 'Cows and Sequence', contest_id : '283', problem_level :  'A' },
    {serial_no: 60, problem_name : 'Little Girl and Maximum Sum',  contest_id :'276', problem_level :  'C' },
    {serial_no: 61, problem_name : 'Booking System',  contest_id :'416', problem_level :  'C' },
    {serial_no: 62, problem_name : 'Barcode',  contest_id :'225', problem_level :  'C' },
    {serial_no: 63, problem_name : 'Arithmetic Progression', contest_id : '382', problem_level :  'C' },
    {serial_no: 64, problem_name : 'Ladder', contest_id : '279', problem_level :  'C' },
    {serial_no: 65, problem_name : "Caesar's Legions",  contest_id :'118', problem_level :  'D' },
    {serial_no: 66, problem_name : 'Xenia and Bit Operations',  contest_id :'339', problem_level :  'D' },
    {serial_no: 67, problem_name : 'Tetrahedron', contest_id : '166', problem_level :  'E' },
    {serial_no: 68, problem_name : 'George and Job',  contest_id :'467', problem_level :  'C' },
    {serial_no: 69, problem_name : 'Good Sequences', contest_id : '264', problem_level :  'B' },
    {serial_no: 70, problem_name : 'Xenia and Weights', contest_id : '339', problem_level :  'C' },
    {serial_no: 71, problem_name : 'Greg and Graph', contest_id : '295', problem_level :  'B' },
    {serial_no: 72, problem_name : 'Number of Ways',  contest_id :'466', problem_level :  'C' },
    {serial_no: 73, problem_name : 'Pair of Numbers', contest_id : '359', problem_level :  'D' },
    {serial_no: 74, problem_name : 'Wonder Room', contest_id : '466', problem_level :  'B' },
    {serial_no: 75, problem_name : "Pashmak and Parmida's problem",  contest_id :'459', problem_level :  'D' },
    {serial_no: 76, problem_name : 'Ice Cave',  contest_id :'540', problem_level :  'C' },
    {serial_no: 77, problem_name : 'Devu and his Brother',  contest_id :'439', problem_level :  'D' },
    {serial_no: 78, problem_name : 'Dima and Bacteria',  contest_id :'400', problem_level :  'D' },
    {serial_no: 79, problem_name : 'Watto and Mechanism',  contest_id :'514', problem_level :  'C' },
    {serial_no: 80, problem_name : 'Restore Graph',  contest_id :'404', problem_level :  'C' },
    {serial_no: 81, problem_name : 'Riding in a Lift', contest_id : '479', problem_level :  'E' },
    {serial_no: 82, problem_name : 'Count Good Substrings', contest_id : '451', problem_level :  'D' },
    {serial_no: 83, problem_name : 'Roman and Numbers', contest_id : '401', problem_level :  'D' },
    {serial_no: 84, problem_name : 'Choosing Capital for Treeland',  contest_id :'219', problem_level :  'D' },
    {serial_no: 85, problem_name : 'Devu and Partitioning of the Array',  contest_id :'439', problem_level :  'C' },
    {serial_no: 86, problem_name : 'Valid Sets', contest_id : '486', problem_level :  'D' },
    {serial_no: 87, problem_name : 'MUH and Cube Walls',  contest_id :'471', problem_level :  'D' },
    {serial_no: 88, problem_name : 'Painting Fence',  contest_id :'448', problem_level :  'C' },
    {serial_no: 89, problem_name : 'XOR on Segment', contest_id : '242', problem_level :  'E' },
    {serial_no: 90, problem_name : 'Vessels', contest_id : '371', problem_level :  'D' },
    {serial_no: 91, problem_name : 'Bad Luck Island', contest_id : '540', problem_level :  'D' },
    {serial_no: 92, problem_name : 'Multiplication Table',  contest_id :'448', problem_level :  'D' },
    {serial_no: 93, problem_name : 'Red-Green Towers',  contest_id :'478', problem_level :  'D' },
    {serial_no: 94, problem_name : 'Pashmak and Buses', contest_id : '459', problem_level :  'C' },
    {serial_no: 95, problem_name : 'Bag of mice',  contest_id :'148', problem_level :  'D' },
    {serial_no: 96, problem_name : 'Gargari and Bishops', contest_id : '463', problem_level :  'C' },
    {serial_no: 97, problem_name : 'Gargari and Permutations',  contest_id :'463', problem_level :  'D' },
    {serial_no: 98, problem_name : 'R2D2 and Droid Army', contest_id : '514', problem_level :  'D' },
    {serial_no: 99, problem_name : 'Bear and Prime Numbers', contest_id : '385', problem_level :  'C' },
    {serial_no: 100, problem_name : 'Good Substrings', contest_id : '271', problem_level :  'D' }
  ]

  module.exports = {ladderproblems}