
  ladderproblems = [
    {serial_no: 1,  problem_name :'Candy Bags',  contest_id :'334', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Word', contest_id : '59', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Dreamoon and Stairs', contest_id : '476', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Cut Ribbon',  contest_id :'189', problem_level :  'A' },
    {serial_no: 5,  problem_name :'T-primes', contest_id : '230', problem_level :  'B' },
    {serial_no: 6,  problem_name :'Ice Skating',  contest_id :'217', problem_level :  'A' },
    {serial_no: 7,  problem_name :'Little Elephant and Bits', contest_id : '258', problem_level :  'A' },
    {serial_no: 8,  problem_name :'Dreamoon and WiFi', contest_id : '476', problem_level :  'B' },
    {serial_no: 9,  problem_name :'Party',  contest_id :'115', problem_level :  'A' },
    {serial_no: 10, problem_name : 'Greg and Array', contest_id : '295', problem_level :  'A' },
    {serial_no: 11, problem_name : 'Table Decorations', contest_id : '478', problem_level :  'C' },
    {serial_no: 12, problem_name : 'Checkposts',  contest_id :'427', problem_level :  'C' },
    {serial_no: 13, problem_name : 'Valera and Elections',  contest_id :'369', problem_level :  'C' },
    {serial_no: 14, problem_name : 'Psychos in a Line', contest_id : '319', problem_level :  'B' },
    {serial_no: 15, problem_name : 'Counting Rectangles is Fun',  contest_id :'372', problem_level :  'B' },
    {serial_no: 16, problem_name : 'Greg and Graph',  contest_id :'295', problem_level :  'B' },
    {serial_no: 17, problem_name : 'Little Girl and Maximum Sum', contest_id : '276', problem_level :  'C' },
    {serial_no: 18, problem_name : 'Renting Bikes',  contest_id :'363', problem_level :  'D' },
    {serial_no: 19, problem_name : 'Treasure', contest_id : '494', problem_level :  'A' },
    {serial_no: 20, problem_name : 'DZY Loves Sequences', contest_id : '446', problem_level :  'A' },
    {serial_no: 21, problem_name : 'Color the Fence', contest_id : '349', problem_level :  'B' },
    {serial_no: 22, problem_name : 'Colorful Graph', contest_id : '246', problem_level :  'D' },
    {serial_no: 23, problem_name : 'Zero Tree',  contest_id :'274', problem_level :  'B' },
    {serial_no: 24, problem_name : "King's Path",  contest_id :'242', problem_level :  'C' },
    {serial_no: 25, problem_name : 'Interesting Array',  contest_id :'482', problem_level :  'B' },
    {serial_no: 26, problem_name : 'Greenhouse Effect', contest_id : '269', problem_level :  'B' },
    {serial_no: 27, problem_name : 'The Brand New Function',  contest_id :'243', problem_level :  'A' },
    {serial_no: 28, problem_name : "Caesar's Legions",  contest_id :'118', problem_level :  'D' },
    {serial_no: 29, problem_name : 'Dima and Hares',  contest_id :'358', problem_level :  'D' },
    {serial_no: 30, problem_name : 'Almost Arithmetical Progression', contest_id : '255', problem_level :  'C' },
    {serial_no: 31, problem_name : 'Hamburgers', contest_id : '371', problem_level :  'C' },
    {serial_no: 32, problem_name : 'Petya and Divisors',  contest_id :'111', problem_level :  'B' },
    {serial_no: 33, problem_name : 'Matrix', contest_id : '364', problem_level :  'A' },
    {serial_no: 34, problem_name : 'Xenia and Weights', contest_id : '339', problem_level :  'C' },
    {serial_no: 35, problem_name : 'Barcode', contest_id : '225', problem_level :  'C' },
    {serial_no: 36, problem_name : 'Color Stripe', contest_id : '219', problem_level :  'C' },
    {serial_no: 37, problem_name : 'Xenia and Bit Operations', contest_id : '339', problem_level :  'D' },
    {serial_no: 38, problem_name : 'Ciel and Robot',  contest_id :'321', problem_level :  'A' },
    {serial_no: 39, problem_name : 'Little Elephant and Interval',  contest_id :'204', problem_level :  'A' },
    {serial_no: 40, problem_name : 'Little Elephant and Cards',  contest_id :'204', problem_level :  'B' },
    {serial_no: 41, problem_name : 'Good Sequences',  contest_id :'264', problem_level :  'B' },
    {serial_no: 42, problem_name : 'k-Tree', contest_id : '431', problem_level :  'C' },
    {serial_no: 43, problem_name : 'Mike and Feet', contest_id : '547', problem_level :  'B' },
    {serial_no: 44, problem_name : 'Andrey and Problem', contest_id : '442', problem_level :  'B' },
    {serial_no: 45, problem_name : 'Maximum Submatrix 2',  contest_id :'375', problem_level :  'B' },
    {serial_no: 46, problem_name : 'Password', contest_id : '126', problem_level :  'B' },
    {serial_no: 47, problem_name : 'Good Substrings', contest_id : '271', problem_level :  'D' },
    {serial_no: 48, problem_name : 'GukiZ hates Boxes',  contest_id :'551', problem_level :  'C' },
    {serial_no: 49, problem_name : 'Regular Bridge',  contest_id :'550', problem_level :  'D' },
    {serial_no: 50, problem_name : 'MUH and Cube Walls',  contest_id :'471', problem_level :  'D' },
    {serial_no: 51, problem_name : 'Little Pony and Harmony Chest',  contest_id :'453', problem_level :  'B' },
    {serial_no: 52, problem_name : 'Sereja and Brackets', contest_id : '380', problem_level :  'C' },
    {serial_no: 53, problem_name : 'Obsessive String', contest_id : '494', problem_level :  'B' },
    {serial_no: 54, problem_name : 'Gargari and Bishops',  contest_id :'463', problem_level :  'C' },
    {serial_no: 55, problem_name : 'Appleman and Tree',  contest_id :'461', problem_level :  'B' },
    {serial_no: 56, problem_name : 'Soldier and Number Game', contest_id : '546', problem_level :  'D' },
    {serial_no: 57, problem_name : 'Lucky Tree',  contest_id :'109', problem_level :  'C' },
    {serial_no: 58, problem_name : 'Missile Silos', contest_id : '144', problem_level :  'D' },
    {serial_no: 59, problem_name : 'Sereja and the Arrangement of Numbers',  contest_id :'367', problem_level :  'C' },
    {serial_no: 60, problem_name : 'Enemy is weak',  contest_id :'61', problem_level :  'E' },
    {serial_no: 61, problem_name : 'A and B and Interesting Substrings', contest_id : '519', problem_level :  'D' },
    {serial_no: 62, problem_name : 'Equivalent Strings',  contest_id :'559', problem_level :  'B' },
    {serial_no: 63, problem_name : 'Book of Evil', contest_id : '337', problem_level :  'D' },
    {serial_no: 64, problem_name : 'Dima and Bacteria', contest_id : '400', problem_level :  'D' },
    {serial_no: 65, problem_name : 'Present', contest_id : '460', problem_level :  'C' },
    {serial_no: 66, problem_name : 'Ciel the Commander',  contest_id :'321', problem_level :  'C' },
    {serial_no: 67, problem_name : 'Pashmak and Buses', contest_id : '459', problem_level :  'C' },
    {serial_no: 68, problem_name : "Pashmak and Parmida's problem",  contest_id :'459', problem_level :  'D' },
    {serial_no: 69, problem_name : 'Count Good Substrings',  contest_id :'451', problem_level :  'D' },
    {serial_no: 70, problem_name : 'Book of Evil',  contest_id :'337', problem_level :  'D' },
    {serial_no: 71, problem_name : 'Civilization',  contest_id :'455', problem_level :  'C' },
    {serial_no: 72, problem_name : 'Painting Fence', contest_id : '448', problem_level :  'C' },
    {serial_no: 73, problem_name : 'A and B and Lecture Rooms',  contest_id :'519', problem_level :  'E' },
    {serial_no: 74, problem_name : 'Water Tree',  contest_id :'343', problem_level :  'D' },
    {serial_no: 75, problem_name : 'Choosing Balls', contest_id : '264', problem_level :  'C' },
    {serial_no: 76, problem_name : 'Watto and Mechanism', contest_id : '514', problem_level :  'C' },
    {serial_no: 77, problem_name : 'Multiplication Table',  contest_id :'448', problem_level :  'D' },
    {serial_no: 78, problem_name : 'Characteristics of Rectangles',  contest_id :'333', problem_level :  'D' },
    {serial_no: 79, problem_name : 'Lucky Common Subsequence',  contest_id :'346', problem_level :  'B' },
    {serial_no: 80, problem_name : 'Prefixes and Suffixes',  contest_id :'432', problem_level :  'D' },
    {serial_no: 81, problem_name : 'Sereja ans Anagrams', contest_id : '367', problem_level :  'B' },
    {serial_no: 82, problem_name : 'XOR on Segment', contest_id : '242', problem_level :  'E' },
    {serial_no: 83, problem_name : 'Porcelain',  contest_id :'148', problem_level :  'E' },
    {serial_no: 84, problem_name : 'Devu and his Brother',  contest_id :'439', problem_level :  'D' },
    {serial_no: 85, problem_name : 'Eternal Victory', contest_id : '61', problem_level :  'D' },
    {serial_no: 86, problem_name : 'Red-Green Towers', contest_id : '478', problem_level :  'D' },
    {serial_no: 87, problem_name : 'Choosing Capital for Treeland',  contest_id :'219', problem_level :  'D' },
    {serial_no: 88, problem_name : 'Roman and Numbers', contest_id : '401', problem_level :  'D' },
    {serial_no: 89, problem_name : 'Vessels',  contest_id :'371', problem_level :  'D' },
    {serial_no: 90, problem_name : 'Propagating tree',  contest_id :'383', problem_level :  'C' },
    {serial_no: 91, problem_name : 'Bag of mice', contest_id : '148', problem_level :  'D' },
    {serial_no: 92, problem_name : 'A Lot of Games', contest_id : '455', problem_level :  'B' },
    {serial_no: 93, problem_name : 'Pair of Numbers', contest_id : '359', problem_level :  'D' },
    {serial_no: 94, problem_name : 'Pashmak and Graph', contest_id : '459', problem_level :  'E' },
    {serial_no: 95, problem_name : 'Petr#',  contest_id :'113', problem_level :  'B' },
    {serial_no: 96, problem_name : 'The Child and Sequence',  contest_id :'438', problem_level :  'D' },
    {serial_no: 97, problem_name : 'Vasya and Beautiful Arrays',  contest_id :'354', problem_level :  'C' },
    {serial_no: 98, problem_name : 'Little Girl and Problem on Trees',  contest_id :'276', problem_level :  'E' },
    {serial_no: 99, problem_name : 'Antimatter', contest_id : '383', problem_level :  'D' },
    {serial_no: 100, problem_name : 'Tree Requests',  contest_id :'570', problem_level :  'D' }
  ]

  module.exports = {ladderproblems}