
  ladderproblems = [
    {serial_no: 1,  problem_name :'Anton and Letters', contest_id : '443', problem_level :  'A' },
    {serial_no: 2,  problem_name :'Way Too Long Words', contest_id : '71', problem_level :  'A' },
    {serial_no: 3,  problem_name :'Young Physicist', contest_id : '69', problem_level :  'A' },
    {serial_no: 4,  problem_name :'Coder',  contest_id :'384', problem_level :  'A' },
    {serial_no: 5,  problem_name :'Collecting Beats is Fun', contest_id : '373', problem_level :  'A' },
    {serial_no: 6,  problem_name :'Fox and Cross',  contest_id :'389', problem_level :  'B' },
    {serial_no: 7,  problem_name :'Archer', contest_id : '312', problem_level :  'B' },
    {serial_no: 8,  problem_name :'Sereja and Suffixes', contest_id : '368', problem_level :  'B' },
    {serial_no: 9,  problem_name :'Ladder',  contest_id :'279', problem_level :  'C' },
    {serial_no: 10, problem_name : 'Color the Fence',  contest_id :'349', problem_level :  'B' },
    {serial_no: 11, problem_name : 'Vasya and Robot',  contest_id :'354', problem_level :  'A' },
    {serial_no: 12, problem_name : 'Fools and Roads', contest_id : '191', problem_level :  'C' },
    {serial_no: 13, problem_name : 'Dima and Hares',  contest_id :'358', problem_level :  'D' },
    {serial_no: 14, problem_name : 'Xenia and Weights', contest_id : '339', problem_level :  'C' },
    {serial_no: 15, problem_name : 'Inna and Dima',  contest_id :'374', problem_level :  'C' },
    {serial_no: 16, problem_name : 'Cows and Sequence',  contest_id :'283', problem_level :  'A' },
    {serial_no: 17, problem_name : 'Psychos in a Line', contest_id : '319', problem_level :  'B' },
    {serial_no: 18, problem_name : 'Greg and Graph',  contest_id :'295', problem_level :  'B' },
    {serial_no: 19, problem_name : 'Number of Ways',  contest_id :'466', problem_level :  'C' },
    {serial_no: 20, problem_name : 'Working out', contest_id : '429', problem_level :  'B' },
    {serial_no: 21, problem_name : 'Read Time',  contest_id :'343', problem_level :  'C' },
    {serial_no: 22, problem_name : 'Cow Program',  contest_id :'283', problem_level :  'B' },
    {serial_no: 23, problem_name : 'LCM Challenge', contest_id : '235', problem_level :  'A' },
    {serial_no: 24, problem_name : 'Bubble Sort Graph', contest_id : '340', problem_level :  'D' },
    {serial_no: 25, problem_name : 'Beautiful Numbers', contest_id : '300', problem_level :  'C' },
    {serial_no: 26, problem_name : 'Counting Kangaroos is Fun', contest_id : '372', problem_level :  'A' },
    {serial_no: 27, problem_name : 'Little Girl and Maximum Sum', contest_id : '276', problem_level :  'C' },
    {serial_no: 28, problem_name : 'Little Girl and Maximum XOR', contest_id : '276', problem_level :  'D' },
    {serial_no: 29, problem_name : 'No to Palindromes!',  contest_id :'464', problem_level :  'A' },
    {serial_no: 30, problem_name : 'George and Job', contest_id : '467', problem_level :  'C' },
    {serial_no: 31, problem_name : 'Matrix',  contest_id :'364', problem_level :  'A' },
    {serial_no: 32, problem_name : 'Round Table Knights',  contest_id :'71', problem_level :  'C' },
    {serial_no: 33, problem_name : "Caesar's Legions", contest_id : '118', problem_level :  'D' },
    {serial_no: 34, problem_name : 'Zero Tree',  contest_id :'274', problem_level :  'B' },
    {serial_no: 35, problem_name : 'Maximum Submatrix 2',  contest_id :'375', problem_level :  'B' },
    {serial_no: 36, problem_name : 'Password', contest_id : '126', problem_level :  'B' },
    {serial_no: 37, problem_name : 'Book of Evil',  contest_id :'337', problem_level :  'D' },
    {serial_no: 38, problem_name : 'Lucky Tree', contest_id : '109', problem_level :  'C' },
    {serial_no: 39, problem_name : 'Jzzhu and Cities',  contest_id :'449', problem_level :  'B' },
    {serial_no: 40, problem_name : 'Ciel and Duel', contest_id : '321', problem_level :  'B' },
    {serial_no: 41, problem_name : 'Array and Operations',  contest_id :'498', problem_level :  'C' },
    {serial_no: 42, problem_name : 'Increase Sequence', contest_id :'466', problem_level :  'D' },
    {serial_no: 43, problem_name : 'Choosing Capital for Treeland', contest_id : '219', problem_level :  'D' },
    {serial_no: 44, problem_name : 'Fox and Minimal path', contest_id : '388', problem_level :  'B' },
    {serial_no: 45, problem_name : 'Kalila and Dimna in the Logging Industry',  contest_id :'319', problem_level :  'C' },
    {serial_no: 46, problem_name : 'Vessels',  contest_id :'371', problem_level :  'D' },
    {serial_no: 47, problem_name : 'Greg and Friends',  contest_id :'295', problem_level :  'C' },
    {serial_no: 48, problem_name : 'Sereja and the Arrangement of Numbers', contest_id : '367', problem_level :  'C' },
    {serial_no: 49, problem_name : 'Super M', contest_id : '592', problem_level :  'D' },
    {serial_no: 50, problem_name : 'Count Good Substrings',  contest_id :'451', problem_level :  'D' },
    {serial_no: 51, problem_name : 'Roman and Numbers', contest_id : '401', problem_level :  'D' },
    {serial_no: 52, problem_name : 'Dima and Bacteria',  contest_id :'400', problem_level :  'D' },
    {serial_no: 53, problem_name : 'Civilization', contest_id : '455', problem_level :  'C' },
    {serial_no: 54, problem_name : 'Enemy is weak', contest_id : '61', problem_level :  'E' },
    {serial_no: 55, problem_name : 'Dima and Salad', contest_id : '366', problem_level :  'C' },
    {serial_no: 56, problem_name : 'Little Elephant and Array',  contest_id :'220', problem_level :  'B' },
    {serial_no: 57, problem_name : 'Prime Number',  contest_id :'359', problem_level :  'C' },
    {serial_no: 58, problem_name : 'Prefixes and Suffixes', contest_id : '432', problem_level :  'D' },
    {serial_no: 59, problem_name : 'A Lot of Games', contest_id : '455', problem_level :  'B' },
    {serial_no: 60, problem_name : 'Ciel the Commander', contest_id : '321', problem_level :  'C' },
    {serial_no: 61, problem_name : 'Painting Fence',  contest_id :'448', problem_level :  'C' },
    {serial_no: 62, problem_name : 'Breaking Good', contest_id : '507', problem_level :  'E' },
    {serial_no: 63, problem_name : 'Eternal Victory', contest_id : '61', problem_level :  'D' },
    {serial_no: 64, problem_name : 'XOR on Segment',  contest_id :'242', problem_level :  'E' },
    {serial_no: 65, problem_name : 'Sereja and Subsequences', contest_id : '314', problem_level :  'C' },
    {serial_no: 66, problem_name : 'Levko and Array',  contest_id :'360', problem_level :  'B' },
    {serial_no: 67, problem_name : 'Gargari and Permutations', contest_id : '463', problem_level :  'D' },
    {serial_no: 68, problem_name : 'Watching Fireworks is Fun', contest_id : '372', problem_level :  'C' },
    {serial_no: 69, problem_name : 'Valid Sets',  contest_id :'486', problem_level :  'D' },
    {serial_no: 70, problem_name : "Pashmak and Parmida's problem", contest_id : '459', problem_level :  'D' },
    {serial_no: 71, problem_name : 'Maximum Value',  contest_id :'484', problem_level :  'B' },
    {serial_no: 72, problem_name : 'Pashmak and Graph', contest_id : '459', problem_level :  'E' },
    {serial_no: 73, problem_name : 'Fox and Card Game',  contest_id :'388', problem_level :  'C' },
    {serial_no: 74, problem_name : 'Strip', contest_id : '487', problem_level :  'B' },
    {serial_no: 75, problem_name : 'Propagating tree', contest_id :'383', problem_level :  'C' },
    {serial_no: 76, problem_name : 'Sausage Maximization', contest_id : '282', problem_level :  'E' },
    {serial_no: 77, problem_name : 'Sereja ans Anagrams', contest_id : '367', problem_level :  'B' },
    {serial_no: 78, problem_name : 'Good Substrings', contest_id : '271', problem_level :  'D' },
    {serial_no: 79, problem_name : 'Appleman and Tree',  contest_id :'461', problem_level :  'B' },
    {serial_no: 80, problem_name : 'MUH and Cube Walls',  contest_id :'471', problem_level :  'D' },
    {serial_no: 81, problem_name : 'Pair of Numbers',  contest_id :'359', problem_level :  'D' },
    {serial_no: 82, problem_name : 'Sereja and Brackets',  contest_id :'380', problem_level :  'C' },
    {serial_no: 83, problem_name : 'Water Tree', contest_id : '343', problem_level :  'D' },
    {serial_no: 84, problem_name : 'Antimatter', contest_id : '383', problem_level :  'D' },
    {serial_no: 85, problem_name : 'LIS of Sequence', contest_id : '486', problem_level :  'E' },
    {serial_no: 86, problem_name : 'The Maths Lecture',  contest_id :'507', problem_level :  'D' },
    {serial_no: 87, problem_name : 'Number Transformation II', contest_id : '346', problem_level :  'C' },
    {serial_no: 88, problem_name : 'Fools and Foolproof Roads',  contest_id :'362', problem_level :  'D' },
    {serial_no: 89, problem_name : 'Lucky Queries',  contest_id :'145', problem_level :  'E' },
    {serial_no: 90, problem_name : 'Caisa and Tree',  contest_id :'463', problem_level :  'E' },
    {serial_no: 91, problem_name : 'Valera and Fools', contest_id : '369', problem_level :  'D' },
    {serial_no: 92, problem_name : 'Blood Cousins', contest_id : '208', problem_level :  'E' },
    {serial_no: 93, problem_name : 'Information Graph',  contest_id :'466', problem_level :  'E' },
    {serial_no: 94, problem_name : 'Vasya and Beautiful Arrays',  contest_id :'354', problem_level :  'C' },
    {serial_no: 95, problem_name : 'Little Girl and Problem on Trees', contest_id : '276', problem_level :  'E' },
    {serial_no: 96, problem_name : 'Valera and Queries', contest_id : '369', problem_level :  'E' },
    {serial_no: 97, problem_name : 'Yaroslav and Divisors', contest_id : '301', problem_level :  'D' },
    {serial_no: 98, problem_name : 'Shaass the Great',  contest_id :'294', problem_level :  'E' },
    {serial_no: 99, problem_name : 'Tree and Queries',  contest_id :'375', problem_level :  'D' },
    {serial_no: 100, problem_name : 'Xenia and Tree',  contest_id :'342', problem_level :  'E' }
  ]

  module.exports = {ladderproblems}